arch: amd64
os: linux
dist: bionic
language: groovy
jdk:
- openjdk11

sudo: false
branches:
  only:
  - master
  - dev
  - develop
  - /^feature\/.*$/
  - /^hotfix\/.*$/
node_js:
      - 16
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

addons:
  chrome: stable
  hosts: devt.ala.org.au

services:
  - elasticsearch
  - mongodb

before_install:
  - export TZ=Australia/Canberra
  - git clone --depth=50 --branch=$ECODATA_CLIENT_PLUGIN_BRANCH https://github.com/AtlasOfLivingAustralia/ecodata-client-plugin.git ../ecodata-client-plugin
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.3-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo sh -c 'echo ES_JAVA_OPTS=\"-Xmx256m -Xms256m\" >> /etc/default/elasticsearch'
  - sudo service elasticsearch restart
  - sudo mkdir -p /data/biocollect
  - sudo chmod o+xw /data
  - sudo chmod o+xw /data/biocollect

install:
  - true

before_script:
  - cd $TRAVIS_BUILD_DIR
  - nvm install 16.15.0
  - nvm use 16.15.0
  - node -v
  - npm install

script:
#  - ./gradlew -PenableClover=true cloverGenerateReport --no-daemon
  - ./gradlew classes
#  - ./src/main/scripts/runFunctionalTests.sh chromeHeadless '/tmp/ecodata' 'feature/newAuthAndJava11'
#  - ./gradlew compileGroovy
  - node_modules/karma/bin/karma start karma.conf.js --single-run --browsers ChromeHeadless
  - ./src/main/scripts/runFunctionalTests.sh
  - cat build/test-results/integrationTest/*.xml

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew clean && travis_wait 30 ./gradlew publish'


env:
  global:
  - ECODATA_CLIENT_PLUGIN_BRANCH="feature/oidc"
  - secure: U/09fO5MoAMmyGXkFZUc6AXi/V1cow3vpWl2LDdp+ddqVdbvDqBr8fj5w9kpQZEwSRBcod7GKxKpB+DXnQj1yjFGnj2Fp34zwcoOPt4pxtJH++dUWNUVNELKrt3cC2CmuUy5zSXEDC6EhVufXb+AySAXHLzwT6/AVbx0iYheWLtik3YqkNZ2Ny75zgvSCc450Ucxdcazc70U7SqnnIthr9HpUxB566JP7lPLw6y0/yHRn8FMDkV3ICYaUnuSJdmsGWw4obagAu+FT9V424GBFPB6qmVfGS9G8IWKV/Was1CdftPbvWPhHtT0NpwpRxnGIQV6xDsFA2hztsc4H9jUvDJ794uvHfU9cjutR4C66+PxGYsohRuTIMz9VeAcPywY5hAtVWB0yFID5mA4yo1VQ3xvJCTknlsRVtVXenhMMQmEqUTRI37dV0czWl9hhjl644xYdfj0T+PSQrEh0NKLBcmmb4fxuI95YOO1IaKoY7+nrskhEyudgVX5Oj5JjV8TP+iXojMT927JN6cILvrprUQbhIVE5srOaZcPElieAvUVMShYfFKLF14EsPh0nkRrjikvMJwiFewomt6TlLpdN4XwTBrG20kKkuijOV7GlgEB7O/zbhfL16m2+lesI9hA7ylavKr1YqxENYa8ESUeurl66M4UJEXxSWbJkkGz08Q=
  - secure: aDQyUOaNj+7D9ug0bhhtnxIbVikKnNrFc2GJe+cRgl0PgPHffuHVGndINcgJW6T3nlLkRwP8Z5Ic9Y2a+C0tzWxiGs2+sHHyw0VaASHzcxV5aH15jgb2MMOY2JkaYVSEp7rvlLeHfLposA1NcvTk9u9nKG0k8R96vTLH3c+cFc6wmKfOFtfUZKu+qi75idaxeHoFQGiNMjU81mzFUA5UeNsNEiazTp8x9HUlqWofOJfrzRzUcp1PKHTV1MJdWyeVDJHg+OWdiWKjA5F/gkpcIFfkxYuvb2WM63wTrYdHBEIfBeGWzFMmbHMwM0SEOkgJQVhEiOfIK67+S/p5hWl/R/gyaf9xj2eZ7DARNNIyuohyXYcOT0gzSoLRXSANU64nrwlgQAJOhHpgFOTdejpZm8XIEOyakCImnJxLjTEivBIujfqT80esomN7rcEj0dulM8uOy1fi4FeyonMyR65ZwduPFaOop93CFSgw9aHlFyRh6Z0n0YNCRbuWLPPRt9ZjaLte7eEIlf87CmS0DDS1vCtKjoHN165K/gpBTltmVZDqBfT70BqVG+DIf3oBZW7scroSlcdJj18axyCIxsPibbCu4ezHgNpM84J2+f7BSaBvKuh00csvu5P0e3h3laHI6jzc0MkWWbV6ZB5e7ctG2fptXIZxse3X0I1tdgL3x08=

