biocollectVersion=9.0.0-SNAPSHOT
grailsVersion=7.2.1
assetPipelineVersion=5.0.34
alaSecurityLibsVersion=8.0.0-SNAPSHOT
seleniumVersion=4.27.0
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx2048M
org.gradle.daemon=true
org.gradle.parallel=true

enableClover=false
inplace=false
metadataExtractorVersion=2.6.2
imgscalrVersion=4.2
httpmimeVersion=4.2.1
jtsVersion=1.8
geoToolsVersion=21.5
