// collection: site
var siteMap =
{
    "projects" : [],
    "siteId" : "",
    "status" : "active",
    "isSciStarter" : false,
    "extent" : {
    "geometry" : {
        "lga" : [
            "Narembeen (S)",
            "Whitehorse (C)",
            "Northern Grampians (S)",
            "Northern Midlands (M)",
            "North Burnett (R)",
            "Paroo (S)",
            "Perenjori (S)",
            "Peppermint Grove (S)",
            "Playford (C)",
            "Pormpuraaw (S)",
            "Port Adelaide Enfield (C)",
            "Port Hedland (T)",
            "Port Augusta (C)",
            "Port Stephens (A)",
            "Redland (C)",
            "Ravensthorpe (S)",
            "Port Macquarie-Hastings (A)",
            "Pyrenees (S)",
            "Port Pirie City and Dists (M)",
            "Port Phillip (C)",
            "Prospect (C)",
            "Gilgandra (A)",
            "Fremantle (C)",
            "Robe (DC)",
            "Singleton (A)",
            "Southern Midlands (M)",
            "Waverley (A)",
            "Nedlands (C)",
            "Cuballing (S)",
            "Lockyer Valley (R)",
            "Sydney (C)",
            "Cootamundra (A)",
            "Stonnington (C)",
            "Queenscliffe (B)",
            "Winton (S)",
            "Macedon Ranges (S)",
            "Kingston (DC)",
            "Deniliquin (A)",
            "Indigo (S)",
            "Morawa (S)",
            "Hay (A)",
            "Cooma-Monaro (A)",
            "Corangamite (S)",
            "Coonamble (A)",
            "Yass Valley (A)",
            "Murray (A)",
            "Burwood (A)",
            "Diamantina (S)",
            "Dorset (M)",
            "Doomadgee (S)",
            "Eurobodalla (A)",
            "Esperance (S)",
            "Elliston (DC)",
            "Kogarah (C)",
            "Mallala (DC)",
            "MacDonnell (S)",
            "Mandurah (C)",
            "Maitland (C)",
            "Manningham (C)",
            "Mapoon (S)",
            "Maroondah (C)",
            "Maribyrnong (C)",
            "Marion (C)",
            "Mount Marshall (S)",
            "George Town (M)",
            "Goulburn Mulwaree (A)",
            "Goyder (DC)",
            "Mount Magnet (S)",
            "Wyong (A)",
            "Sunshine Coast (R)",
            "Strathbogie (S)",
            "Tasman (M)",
            "Tamworth Regional (A)",
            "Tablelands (R)",
            "Tenterfield (A)",
            "Bathurst Regional (A)",
            "Baw Baw (S)",
            "Burnside (C)",
            "Kondinin (S)",
            "Kowanyama (S)",
            "Ku-ring-gai (A)",
            "Lismore (C)",
            "Cottesloe (T)",
            "Cowra (A)",
            "Croydon (S)",
            "Brisbane (C)",
            "Brighton (M)",
            "Brimbank (C)",
            "Canada Bay (A)",
            "Glen Eira (C)",
            "Goondiwindi (R)",
            "Gloucester (A)",
            "Gold Coast (C)",
            "Glenorchy (C)",
            "Hornsby (A)",
            "Hobart (C)",
            "Hindmarsh (S)",
            "Holdfast Bay (C)",
            "Holroyd (C)",
            "Hope Vale (S)",
            "Inverell (A)",
            "Jerramungup (S)",
            "Isaac (R)",
            "Irwin (S)",
            "Ipswich (C)",
            "Jerilderie (A)",
            "Kalamunda (S)",
            "Lower Eyre Peninsula (DC)",
            "Mukinbudin (S)",
            "Murchison (S)",
            "Belmont (C)",
            "Blacktown (C)",
            "Beverley (S)",
            "South Perth (C)",
            "Boulia (S)",
            "Bega Valley (A)",
            "Yarra (C)",
            "Carpentaria (S)",
            "Victoria-Daly (S)",
            "Whittlesea (C)",
            "Darebin (C)",
            "Frankston (C)",
            "Cambridge (T)",
            "Surf Coast (S)",
            "Sutherland Shire (A)",
            "Joondalup (C)",
            "Kent (S)",
            "Kingborough (M)",
            "King Island (M)",
            "Mullewa (S)",
            "Mundaring (S)",
            "Trayning (S)",
            "Alice Springs (T)",
            "Donnybrook-Balingup (S)",
            "Roxby Downs (M)",
            "Wongan-Ballidu (S)",
            "Coober Pedy (DC)",
            "Orroroo/Carrieton (DC)",
            "Narrogin (T)",
            "Gawler (T)",
            "Bland (A)",
            "Torres (S)",
            "South Gippsland (S)",
            "Port Lincoln (C)",
            "Plantagenet (S)",
            "Lockhart River (S)",
            "East Fremantle (T)",
            "Goomalling (S)",
            "Menzies (S)",
            "Claremont (T)",
            "Maralinga Tjarutja (AC)",
            "Broken Hill (C)",
            "Leonora (S)",
            "Grant (DC)",
            "Franklin Harbour (DC)",
            "Dubbo (C)",
            "Belyuen (S)",
            "Kimba (DC)",
            "Katherine (T)",
            "Kalgoorlie/Boulder (C)",
            "Cunderdin (S)",
            "Murrindindi (S)",
            "Narromine (A)",
            "Mount Gambier (C)",
            "West Arthur (S)",
            "Toodyay (S)",
            "Unley (C)",
            "Gosnells (C)",
            "Woorabinda (S)",
            "Mitcham (C)",
            "Charles Sturt (C)",
            "Kentish (M)",
            "Hurstville (C)",
            "Griffith (C)",
            "Mitchell (S)",
            "Mid-Western Regional (A)",
            "Wellington (S)",
            "Corowa Shire (A)",
            "Ryde (C)",
            "Tea Tree Gully (C)",
            "Young (A)",
            "Wingecarribee (A)",
            "Nungarin (S)",
            "Cranbrook (S)",
            "East Gippsland (S)",
            "Gnowangerup (S)",
            "Knox (C)",
            "Manly (A)",
            "Maranoa (R)",
            "West Torrens (C)",
            "Cairns (R)",
            "Cabonne (A)",
            "Mornington Peninsula (S)",
            "Derby-West Kimberley (S)",
            "Wyndham (C)",
            "Wentworth (A)",
            "Scenic Rim (R)",
            "Northampton (S)",
            "Woodanilling (S)",
            "Campaspe (S)",
            "Denmark (S)",
            "Campbelltown (C) (ACT)",
            "Campbelltown (C) (SA)",
            "Lithgow (C)",
            "Gingin (S)",
            "Greater Taree (C)",
            "Devonport (C)",
            "Adelaide Hills (DC)",
            "Gosford (C)",
            "Monash (C)",
            "Wollondilly (A)",
            "Capel (S)",
            "Liverpool (C)",
            "Launceston (C)",
            "Lane Cove (A)",
            "Glamorgan/Spring Bay (M)",
            "Gladstone (R)",
            "Great Lakes (A)",
            "Hepburn (S)",
            "Bayside (C)",
            "Bayswater (C)",
            "Burnie (C)",
            "Broomehill-Tambellup (S)",
            "Narrandera (A)",
            "Mount Alexander (S)",
            "Derwent Valley (M)",
            "Lake Grace (S)",
            "Meekatharra (S)",
            "Dardanup (S)",
            "Northern Peninsula Area (R)",
            "Alpine (S)",
            "Northam (S)",
            "Lachlan (A)",
            "Berrigan (A)",
            "Flinders Ranges (DC)",
            "Waroona (S)",
            "Laverton (S)",
            "Lake Macquarie (C)",
            "Leeton (A)",
            "Dandaragan (S)",
            "Dalwallinu (S)",
            "Dungog (A)",
            "Dowerin (S)",
            "Hinchinbrook (S)",
            "Hobsons Bay (C)",
            "Melton (S)",
            "Guyra (A)",
            "Gunnedah (A)",
            "Strathfield (A)",
            "Corrigin (S)",
            "York (S)",
            "Bulloo (S)",
            "Wudinna (DC)",
            "Mingenew (S)",
            "Fairfield (C)",
            "Cue (S)",
            "Gundagai (A)",
            "Coolgardie (S)",
            "Katanning (S)",
            "Forbes (A)",
            "Dumbleyung (S)",
            "Wickepin (S)",
            "Carnamah (S)",
            "Yilgarn (S)",
            "West Arnhem (S)",
            "Casey (C)",
            "Cassowary Coast (R)",
            "Cleve (DC)",
            "Richmond Valley (A)",
            "Yankalilla (DC)",
            "North Sydney (A)",
            "Collie (S)",
            "Serpentine-Jarrahdale (S)",
            "Somerset (R)",
            "Southern Mallee (DC)",
            "Stirling (C)",
            "The Coorong (DC)",
            "Wagga Wagga (C)",
            "Warren (A)",
            "Wanneroo (C)",
            "Peterborough (DC)",
            "Wujal Wujal (S)",
            "Westonia (S)",
            "Barkly (S)",
            "Sandstone (S)",
            "Palmerston (C)",
            "Horsham (RC)",
            "Armadale (C)",
            "Moora (S)",
            "Orange (C)",
            "Mosman Park (T)",
            "Ngaanyatjarraku (S)",
            "Williams (S)",
            "Yarra Ranges (S)",
            "Central Highlands (M)",
            "Central Highlands (R)",
            "Central Goldfields (S)",
            "Central Desert (S)",
            "Yorke Peninsula (DC)",
            "Chapman Valley (S)",
            "Cherbourg (S)",
            "Chittering (S)",
            "Clare and Gilbert Valleys (DC)",
            "Clarence (C)",
            "Clarence Valley (A)",
            "Coffs Harbour (C)",
            "Colac-Otway (S)",
            "Cobar (A)",
            "Cockburn (C)",
            "Cloncurry (S)",
            "Tammin (S)",
            "Tatiara (DC)",
            "Albany (C)",
            "Augusta-Margaret River (S)",
            "Armidale Dumaresq (A)",
            "Ashburton (S)",
            "Adelaide (C)",
            "Ararat (RC)",
            "Anangu Pitjantjatjara (AC)",
            "Ashfield (A)",
            "The Hills Shire (A)",
            "Tumbarumba (A)",
            "Townsville (C)",
            "Towong (S)",
            "Unincorp. Other Territories",
            "Tweed (A)",
            "Tumby Bay (DC)",
            "Unincorporated SA",
            "Unincorporated NSW",
            "Upper Lachlan Shire (A)",
            "Unincorporated Vic",
            "Upper Hunter Shire (A)",
            "Unincorporated NT",
            "Upper Gascoyne (S)",
            "Vincent (T)",
            "Victoria Plains (S)",
            "Wagait (S)",
            "Wakefield (DC)",
            "Walgett (A)",
            "Waratah/Wynyard (M)",
            "Wangaratta (RC)",
            "Walkerville (M)",
            "Balranald (A)",
            "Ballina (A)",
            "Balonne (S)",
            "Murray (S)",
            "Ballarat (C)",
            "Aurukun (S)",
            "Banana (S)",
            "Bankstown (C)",
            "Murrumbidgee (A)",
            "Warringah (A)",
            "Wandering (S)",
            "Warrumbungle Shire (A)",
            "Wattle Range (DC)",
            "Warrnambool (C)",
            "Weipa (T)",
            "Naracoorte and Lucindale (DC)",
            "Whitsunday (R)",
            "Wodonga (RC)",
            "Wollongong (C)",
            "Greater Geelong (C)",
            "Roebourne (S)",
            "Pingelly (S)",
            "Weddin (A)",
            "Barcoo (S)",
            "Mount Barker (DC)",
            "Koorda (S)",
            "Glen Innes Severn (A)",
            "Pittwater (A)",
            "Greater Hume Shire (A)",
            "Harden (A)",
            "Dundas (S)",
            "Bruce Rock (S)",
            "Oberon (A)",
            "Woollahra (A)",
            "Carnarvon (S)",
            "Hume (C)",
            "Yarrabah (S)",
            "Northern Areas (DC)",
            "Coorow (S)",
            "Copper Coast (DC)",
            "Wiluna (S)",
            "West Coast (M)",
            "Perth (C)",
            "South Burnett (R)",
            "Southern Downs (R)",
            "Wyndham-East Kimberley (S)",
            "Norwood Payneham St Peters (C)",
            "Logan (C)",
            "Darwin (C)",
            "Cardinia (S)",
            "Tumut Shire (A)",
            "Harvey (S)",
            "Flinders (M)",
            "McKinlay (S)",
            "Marrickville (A)",
            "Coomalie (S)",
            "Lockhart (A)",
            "Loddon (S)",
            "Cook (S)",
            "East Arnhem (S)",
            "Hawkesbury (C)",
            "Fraser Coast (R)",
            "Sorell (M)",
            "Glenelg (S)",
            "Bunbury (C)",
            "Onkaparinga (C)",
            "Palerang (A)",
            "Swan (C)",
            "Canterbury (C)",
            "Wellington (A)",
            "Willoughby (C)",
            "Central Darling (A)",
            "Cessnock (C)",
            "Yarriambiack (S)",
            "Circular Head (M)",
            "Charters Towers (R)",
            "Murray Bridge (RC)",
            "Nannup (S)",
            "Muswellbrook (A)",
            "Narrabri (A)",
            "Nambucca (A)",
            "Napranum (S)",
            "Nillumbik (S)",
            "Parkes (A)",
            "Parramatta (C)",
            "Penrith (C)",
            "Queanbeyan (C)",
            "Quilpie (S)",
            "Randwick (C)",
            "Renmark Paringa (DC)",
            "Rockhampton (R)",
            "Ceduna (DC)",
            "Kwinana (T)",
            "Kulin (S)",
            "Conargo (A)",
            "Wyalkatchem (S)",
            "Auburn (C)",
            "Rockingham (C)",
            "Richmond (S)",
            "Rockdale (C)",
            "Shoalhaven (C)",
            "Salisbury (C)",
            "Snowy River (A)",
            "Shark Bay (S)",
            "Southern Grampians (S)",
            "Meander Valley (M)",
            "Mansfield (S)",
            "Berri and Barmera (DC)",
            "Golden Plains (S)",
            "West Tamar (M)",
            "Streaky Bay (DC)",
            "Swan Hill (RC)",
            "Tiwi Islands (S)",
            "Temora (A)",
            "Bridgetown-Greenbushes (S)",
            "Banyule (C)",
            "Bass Coast (S)",
            "Barossa (DC)",
            "Barcaldine (R)",
            "Albury (C)",
            "Moonee Valley (C)",
            "Barunga West (DC)",
            "Byron (A)",
            "Leichhardt (A)",
            "Light (RegC)",
            "Latrobe (M)",
            "Latrobe (C)",
            "Blue Mountains (C)",
            "Blayney (A)",
            "Bogan (A)",
            "Boorowa (A)",
            "Bombala (A)",
            "Boddington (S)",
            "Break O'Day (M)",
            "Brewarrina (A)",
            "Bourke (A)",
            "Boyup Brook (S)",
            "Botany Bay (C)",
            "Canning (C)",
            "Camden (A)",
            "East Pilbara (S)",
            "Etheridge (S)",
            "Greater Bendigo (C)",
            "Gwydir (A)",
            "Kangaroo Island (DC)",
            "Huon Valley (M)",
            "Junee (A)",
            "Manjimup (S)",
            "Mackay (R)",
            "Loxton Waikerie (DC)",
            "Bellingen (A)",
            "Bassendean (T)",
            "Busselton (S)",
            "Buloke (S)",
            "Toowoomba (R)",
            "Three Springs (S)",
            "Newcastle (C)",
            "Kellerberrin (S)",
            "Kiama (A)",
            "Melbourne (C)",
            "Kingston (C)",
            "Roper Gulf (S)",
            "Benalla (RC)",
            "Kojonup (S)",
            "Geraldton-Greenough (C)",
            "Gympie (R)",
            "West Wimmera (S)",
            "Exmouth (S)",
            "Flinders (S)",
            "Carrathool (A)",
            "Yalgoo (S)",
            "Central Coast (M)",
            "Moyne (S)",
            "Murweh (S)",
            "Narrogin (S)",
            "Alexandrina (DC)",
            "Mount Isa (C)",
            "Kempsey (A)",
            "Karoonda East Murray (DC)",
            "Greater Dandenong (C)",
            "Shellharbour (C)",
            "Wagin (S)",
            "Victor Harbor (C)",
            "Uralla (A)",
            "Longreach (R)",
            "Liverpool Plains (A)",
            "Litchfield (M)",
            "Brookton (S)",
            "Moreton Bay (R)",
            "Mount Remarkable (DC)",
            "Halls Creek (S)",
            "Hunters Hill (A)",
            "Greater Shepparton (C)",
            "Moira (S)",
            "Mildura (RC)",
            "Merredin (S)",
            "Mid Murray (DC)",
            "Moorabool (S)",
            "Gannawarra (S)",
            "Moree Plains (A)",
            "Melville (C)",
            "Moreland (C)",
            "Kyogle (A)",
            "Unincorporated ACT",
            "Coolamon (A)",
            "Wakool (A)",
            "Victoria Park (T)",
            "Walcha (A)",
            "Burdekin (S)",
            "Western Downs (R)",
            "Quairading (S)",
            "Mosman (A)",
            "Burke (S)",
            "Bundaberg (R)",
            "Blackall Tambo (R)",
            "Whyalla (C)",
            "Urana (A)",
            "Subiaco (C)",
            "Broome (S)",
            "Boroondara (C)"
        ],
            "nrm" : [
            "South East NSW",
            "North East",
            "Marine NRM",
            "Avon River Basin",
            "Northern Territory",
            "Northern Tablelands",
            "North West NRM Region",
            "Northern Gulf",
            "Northern and Yorke",
            "North West NSW",
            "Murray",
            "Mallee",
            "Mackay Whitsunday",
            "Kangaroo Island",
            "Hunter",
            "Greater Sydney",
            "South West Region",
            "South Coast Region",
            "Rangelands Region",
            "Swan Region",
            "Peel-Harvey Region",
            "Northern Agricultural Region",
            "Wimmera",
            "Wet Tropics",
            "Western",
            "West Gippsland",
            "Torres Strait",
            "Southern Gulf",
            "South West Queensland",
            "South East Queensland",
            "South East",
            "South Australian Murray Darling Basin",
            "South Australian Arid Lands",
            "South NRM Region",
            "Riverina",
            "Port Phillip and Western Port",
            "North Coast",
            "North Central",
            "North NRM Region",
            "Goulburn Broken",
            "Glenelg Hopkins",
            "Fitzroy",
            "Eyre Peninsula",
            "East Gippsland",
            "Desert Channels",
            "Corangamite",
            "Co-operative Management Area",
            "Condamine",
            "Central West",
            "Central Tablelands",
            "Cape York",
            "Burnett Mary",
            "Burdekin",
            "Maranoa Balonne and Border Rivers",
            "Alinytjara Wilurara",
            "Adelaide and Mount Lofty Ranges",
            "ACT"
        ],
            "locality" : "",
            "centre" : [
            "134.48225543571934",
            "-25.71895929990835"
        ],
            "aream2" : 7870871728950.708,
            "pid" : 8943234,
            "state" : [
            "Jervis Bay Territory",
            "Queensland (including Coastal Waters)",
            "Australian Capital Territory",
            "Tasmania (including Coastal Waters)",
            "Western Australia (including Coastal Waters)",
            "Northern Territory (including Coastal Waters)",
            "New South Wales (including Coastal Waters)",
            "South Australia (including Coastal Waters)",
            "Victoria (including Coastal Waters)"
        ],
            "mvs" : "Other tussock grasslands",
            "type" : "pid",
            "mvg" : "Hummock Grasslands",
            "ibra" : [
            "Central Mackay Coast",
            "Ord Victoria Plain",
            "Riverina",
            "Tasmanian Southern Ranges",
            "Gulf Fall and Uplands",
            "Tanami",
            "Pine Creek",
            "Arnhem Plateau",
            "Ben Lomond",
            "Daly Basin",
            "Pilbara",
            "Naracoorte Coastal Plain",
            "Sturt Plateau",
            "Swan Coastal Plain",
            "Simpson Strzelecki Dunefields",
            "Gascoyne",
            "Victorian Volcanic Plain",
            "Yalgoo",
            "Avon Wheatbelt",
            "Brigalow Belt North",
            "Finke",
            "Victorian Midlands",
            "Cobar Peneplain",
            "Great Victoria Desert",
            "Cape York Peninsula",
            "Gibson Desert",
            "Flinders Lofty Block",
            "MacDonnell Ranges",
            "Mount Isa Inlier",
            "Tasmanian Central Highlands",
            "Geraldton Sandplains",
            "Kanmantoo",
            "Darwin Coastal",
            "Gawler",
            "Victoria Bonaparte",
            "Tasmanian South East",
            "Davenport Murchison Ranges",
            "NSW South Western Slopes",
            "Jarrah Forest",
            "Gulf Plains",
            "New England Tablelands",
            "Carnarvon",
            "Murchison",
            "Tasmanian Northern Midlands",
            "Mallee",
            "Broken Hill Complex",
            "Coolgardie",
            "Mulga Lands",
            "Great Sandy Desert",
            "Nandewar",
            "Gulf Coastal",
            "King",
            "Dampierland",
            "Tasmanian Northern Slopes",
            "Australian Alps",
            "Central Ranges",
            "Northern Kimberley",
            "Tasmanian West",
            "South Eastern Highlands",
            "South East Corner",
            "Mitchell Grass Downs",
            "Murray Darling Depression",
            "Brigalow Belt South",
            "Warren",
            "Arnhem Coast",
            "Little Sandy Desert",
            "Eyre Yorke Block",
            "Tiwi Cobourg",
            "Sydney Basin",
            "NSW North Coast",
            "Esperance Plains",
            "Einasleigh Uplands",
            "Burt Plain",
            "Central Kimberley",
            "Hampton",
            "Darling Riverine Plains",
            "Flinders",
            "Channel Country",
            "Wet Tropics",
            "South Eastern Queensland",
            "South East Coastal Plain",
            "Nullarbor",
            "Stony Plains",
            "Desert Uplands",
            "Central Arnhem"
        ],
            "imcra4_pb" : [
            "Southwest Shelf Transition",
            "Northeast Shelf Province",
            "Spencer Gulf Shelf Province",
            "Central Eastern Shelf Transition",
            "Bass Strait Shelf Province",
            "Central Eastern Shelf Province",
            "Great Australian Bight Shelf Transition",
            "Tasmanian Shelf Province",
            "Northwest Shelf Transition",
            "Southwest Shelf Province",
            "Northwest Shelf Province",
            "Central Western Shelf Transition",
            "Northern Shelf Province",
            "Northeast Shelf Transition",
            "Central Western Shelf Province",
            "Southeast Shelf Transition",
            "Western Bass Strait Shelf Transition"
        ],
            "elect" : [
            "FADDEN",
            "GROOM",
            "MAYO",
            "LONGMAN",
            "FAIRFAX",
            "GREY",
            "FISHER",
            "MARANOA",
            "HINKLER",
            "WIDE BAY",
            "FLYNN",
            "HERBERT",
            "KENNEDY",
            "DURACK",
            "DAWSON",
            "BRADDON",
            "BRUCE",
            "GILMORE",
            "WHITLAM",
            "HUME",
            "CUNNINGHAM",
            "HUGHES",
            "COOK",
            "MACARTHUR",
            "FARRER",
            "GOLDSTEIN",
            "ASTON",
            "KINGSFORD SMITH",
            "NORTH SYDNEY",
            "WARRINGAH",
            "BENNELONG",
            "PARRAMATTA",
            "WERRIWA",
            "FOWLER",
            "MCMAHON",
            "BRADFIELD",
            "MACKELLAR",
            "BEROWRA",
            "GREENWAY",
            "CHIFLEY",
            "MITCHELL",
            "LINDSAY",
            "ROBERTSON",
            "MACQUARIE",
            "DOBELL",
            "WATSON",
            "BLAXLAND",
            "WENTWORTH",
            "SHORTLAND",
            "CALARE",
            "RIVERINA",
            "NEWCASTLE",
            "PATERSON",
            "HUNTER",
            "PARKES",
            "HOTHAM",
            "CASEY",
            "REID",
            "EDEN-MONARO",
            "CHISHOLM",
            "LYNE",
            "NEW ENGLAND",
            "HIGGINS",
            "DEAKIN",
            "COWPER",
            "PAGE",
            "SYDNEY",
            "GRAYNDLER",
            "RICHMOND",
            "CANBERRA",
            "FENNER",
            "BEAN",
            "SWAN",
            "CURTIN",
            "STIRLING",
            "COWAN",
            "MOORE",
            "PEARCE",
            "FORREST",
            "O'CONNOR",
            "MONASH",
            "HOLT",
            "DUNKLEY",
            "LA TROBE",
            "ISAACS",
            "CORIO",
            "COOPER",
            "JAGAJAGA",
            "SCULLIN",
            "WILLS",
            "MARIBYRNONG",
            "FRASER",
            "GORTON",
            "CALWELL",
            "BALLARAT",
            "MCEWEN",
            "INDI",
            "BENDIGO",
            "NICHOLLS",
            "KOOYONG",
            "CORANGAMITE",
            "WANNON",
            "MALLEE",
            "LALOR",
            "MACNAMARA",
            "GELLIBRAND",
            "CLARK",
            "LYONS",
            "FLINDERS",
            "FRANKLIN",
            "BASS",
            "KINGSTON",
            "BOOTHBY",
            "STURT",
            "ADELAIDE",
            "MAKIN",
            "HINDMARSH",
            "SPENCE",
            "MCPHERSON",
            "MONCRIEFF",
            "RANKIN",
            "MORETON",
            "OXLEY",
            "BOWMAN",
            "GRIFFITH",
            "CANNING",
            "MELBOURNE",
            "MENZIES",
            "BARTON",
            "BANKS",
            "BURT",
            "TANGNEY",
            "BRAND",
            "FREMANTLE",
            "HASLUCK",
            "PERTH",
            "BRISBANE",
            "FORDE",
            "WRIGHT",
            "BARKER",
            "RYAN",
            "LEICHHARDT",
            "SOLOMON",
            "CAPRICORNIA",
            "LINGIARI",
            "GIPPSLAND",
            "LILLEY",
            "PETRIE",
            "DICKSON",
            "BLAIR",
            "BONNER"
        ],
            "cmz" : [
            "Naracoorte woodlands",
            "South Western Australia temperate woodlands",
            "Eastern Australia mulga shrublands",
            "Brigalow woodlands",
            "Eastern Australia tropical rainforests",
            "Eastern Australia woodlands",
            "Eastern Australia temperate and subtropical forests",
            "Swan Coastal Plain shrublands and woodlands",
            "Tasman temperate forests",
            "Tasman temperate rainforests and highland forests",
            "South Eastern Australia mallee woodlands",
            "South Eastern Australia mixed temperate forests woodlands and grasslands",
            "Mitchell grasslands",
            "North Australian tropical savanna woodlands",
            "Western Australian temperate sandplain woodlands",
            "Arid shrublands and desert",
            "North Eastern Australia tropical rainforests",
            "South Australian Eucalypt woodlands",
            "Esperance coastal shrublands and mallee",
            "South Eastern Australia temperate woodlands",
            "Australian Alps montane grasslands and heathlands",
            "South Western Australia temperate forests",
            "South Western Australia mallee woodlands"
        ],
            "other" : [
            "Australian Coral Ecoregions",
            "RAMSAR wetland regions",
            "Directory of Important Wetlands",
            "ACT TAMS Reserves",
            "NSW Local Land Services Regions",
            "National Native Title Register (NNTR, Determinations of Native Title) - boundaries and core attributes",
            "Atlas of Life in the Coastal Wilderness",
            "Great Eastern Ranges Initiative",
            "Indigenous Protected Areas 2013",
            "Indigenous Land Use Agreements"
        ],
            "gerSubRegion" : [
            "GER Border Ranges",
            "GER Illawarra to Shoalhaven",
            "GER Southern Highlands",
            "GER Hunter Valley",
            "GER Jaliigirr",
            "GER Central Victorial Biolinks",
            "GER Kosciuszko to Coast",
            "GER Slopes To Summit",
            "GER Victorian BioLinks"
        ]
    },
    "source" : "pid"
},
    "name" : "Nesp Hub Site 1",
    "description" : "No description supplied"
};
