var sitePropertiesToUpdate = {
    "extent": {
        "geometry": {
            "datum": "",
            "fid": "cl1083",
            "areaKmSq": 2743274.2507439414,
            "precision": "",
            "lga": [
                "Kangaroo Island (DC)",
                "Rockingham (C)",
                "Fraser Coast (R)",
                "Yarrabah (S)",
                "Glenorchy (C)",
                "Rockdale (C)",
                "Dundas (S)",
                "Devonport (C)",
                "Franklin Harbour (DC)",
                "Grant (DC)",
                "Ku-ring-gai (A)",
                "Kowanyama (S)",
                "Lismore (C)",
                "Kingston (DC)",
                "Nedlands (C)",
                "Gold Coast (C)",
                "Parramatta (C)",
                "Bunbury (C)",
                "Jerramungup (S)",
                "Port Lincoln (C)",
                "South Gippsland (S)",
                "Bega Valley (A)",
                "Belmont (C)",
                "Kogarah (C)",
                "Waratah/Wynyard (M)",
                "Unincorporated Vic",
                "Yorke Peninsula (DC)",
                "Yankalilla (DC)",
                "Carnamah (S)",
                "Fremantle (C)",
                "Wellington (S)",
                "Kempsey (A)",
                "Alexandrina (DC)",
                "Gympie (R)",
                "Roper Gulf (S)",
                "Kingston (C)",
                "Central Coast (M)",
                "Kiama (A)",
                "Mackay (R)",
                "Shark Bay (S)",
                "Hawkesbury (C)",
                "Melville (C)",
                "Botany Bay (C)",
                "East Arnhem (S)",
                "Barunga West (DC)",
                "Canada Bay (A)",
                "Sutherland Shire (A)",
                "Surf Coast (S)",
                "Cambridge (T)",
                "Victoria-Daly (S)",
                "Carpentaria (S)",
                "Wyong (A)",
                "Mallala (DC)",
                "Dorset (M)",
                "Robe (DC)",
                "Whitsunday (R)",
                "Unincorporated NT",
                "Chapman Valley (S)",
                "North Sydney (A)",
                "Richmond Valley (A)",
                "Waroona (S)",
                "Great Lakes (A)",
                "Gladstone (R)",
                "Glamorgan/Spring Bay (M)",
                "Pittwater (A)",
                "Brighton (M)",
                "Brisbane (C)",
                "Sunshine Coast (R)",
                "Tasman (M)",
                "Roebourne (S)",
                "Greater Geelong (C)",
                "Wollongong (C)",
                "Northern Peninsula Area (R)",
                "Salisbury (C)",
                "Derwent Valley (M)",
                "Napranum (S)",
                "Nambucca (A)",
                "Nannup (S)",
                "Murray Bridge (RC)",
                "Circular Head (M)",
                "Lane Cove (A)",
                "Capel (S)",
                "Frankston (C)",
                "Corangamite (S)",
                "Onkaparinga (C)",
                "Logan (C)",
                "Flinders (M)",
                "Coorow (S)",
                "Gosford (C)",
                "Greater Taree (C)",
                "Gingin (S)",
                "Denmark (S)",
                "Burnie (C)",
                "Bayswater (C)",
                "Bayside (C)",
                "Launceston (C)",
                "Torres Strait Island (R)",
                "Claremont (T)",
                "East Fremantle (T)",
                "Lockhart River (S)",
                "Torres (S)",
                "Hope Vale (S)",
                "Waverley (A)",
                "Lower Eyre Peninsula (DC)",
                "Irwin (S)",
                "Isaac (R)",
                "Holdfast Bay (C)",
                "Hobart (C)",
                "Hornsby (A)",
                "Cottesloe (T)",
                "Marion (C)",
                "Maribyrnong (C)",
                "Mapoon (S)",
                "Maitland (C)",
                "Mandurah (C)",
                "Elliston (DC)",
                "Esperance (S)",
                "Eurobodalla (A)",
                "Doomadgee (S)",
                "Queenscliffe (B)",
                "Sydney (C)",
                "Warringah (A)",
                "Wattle Range (DC)",
                "Ravensthorpe (S)",
                "Redland (C)",
                "Port Stephens (A)",
                "Port Augusta (C)",
                "Port Hedland (T)",
                "Port Adelaide Enfield (C)",
                "Pormpuraaw (S)",
                "Playford (C)",
                "Port Macquarie-Hastings (A)",
                "Port Phillip (C)",
                "Port Pirie City and Dists (M)",
                "Peppermint Grove (S)",
                "Wagait (S)",
                "Palm Island (S)",
                "Weipa (T)",
                "Warrnambool (C)",
                "Aurukun (S)",
                "Murray (S)",
                "Ballina (A)",
                "Vincent (T)",
                "Unincorporated NSW",
                "Unincorporated SA",
                "Tumby Bay (DC)",
                "Tweed (A)",
                "Unincorp. Other Territories",
                "Townsville (C)",
                "The Hills Shire (A)",
                "Ashfield (A)",
                "Ashburton (S)",
                "Augusta-Margaret River (S)",
                "Albany (C)",
                "Cockburn (C)",
                "Colac-Otway (S)",
                "Coffs Harbour (C)",
                "Clarence Valley (A)",
                "Clarence (C)",
                "Mosman Park (T)",
                "Palmerston (C)",
                "Wanneroo (C)",
                "The Coorong (DC)",
                "Stirling (C)",
                "Cleve (DC)",
                "Cassowary Coast (R)",
                "Casey (C)",
                "West Arnhem (S)",
                "Lake Macquarie (C)",
                "Hobsons Bay (C)",
                "Hinchinbrook (S)",
                "Dandaragan (S)",
                "Derby-West Kimberley (S)",
                "Charles Sturt (C)",
                "Northampton (S)",
                "East Gippsland (S)",
                "King Island (M)",
                "Kingborough (M)",
                "Joondalup (C)",
                "Wyndham (C)",
                "South Perth (C)",
                "Hunters Hill (A)",
                "Victor Harbor (C)",
                "Shellharbour (C)",
                "Litchfield (M)",
                "Mornington (S)",
                "Mosman (A)",
                "Burdekin (S)",
                "Moyne (S)",
                "Geraldton-Greenough (C)",
                "George Town (M)",
                "Glenelg (S)",
                "Melbourne (C)",
                "Newcastle (C)",
                "Mount Remarkable (DC)",
                "Moreton Bay (R)",
                "Broome (S)",
                "Subiaco (C)",
                "Whyalla (C)",
                "Bundaberg (R)",
                "Burke (S)",
                "Exmouth (S)",
                "Manjimup (S)",
                "West Tamar (M)",
                "Busselton (S)",
                "East Pilbara (S)",
                "Break O'Day (M)",
                "Byron (A)",
                "Streaky Bay (DC)",
                "Shoalhaven (C)",
                "Auburn (C)",
                "Kwinana (T)",
                "Ceduna (DC)",
                "Rockhampton (R)",
                "Randwick (C)",
                "Victoria Park (T)",
                "Willoughby (C)",
                "Sorell (M)",
                "Cook (S)",
                "Harvey (S)",
                "Cardinia (S)",
                "Darwin (C)",
                "Wyndham-East Kimberley (S)",
                "West Coast (M)",
                "Copper Coast (DC)",
                "Perth (C)",
                "Woollahra (A)",
                "Carnarvon (S)",
                "Bellingen (A)",
                "Huon Valley (M)",
                "Canning (C)",
                "Latrobe (M)",
                "Leichhardt (A)",
                "Bass Coast (S)",
                "Tiwi Islands (S)",
                "Cairns (R)",
                "Manly (A)",
                "Ryde (C)",
                "Mornington Peninsula (S)"
            ],
            "bbox": "POLYGON((109.23348002808092 -47.193641170803346,109.23348002808092 -8.883333333166718,163.1920849105902 -8.883333333166718,163.1920849105902 -47.193641170803346,109.23348002808092 -47.193641170803346))",
            "nrm": [
                "Hunter",
                "Northern and Yorke",
                "Northern Gulf",
                "North West NRM Region",
                "Northern Territory",
                "South East Queensland",
                "Southern Gulf",
                "Torres Strait",
                "West Gippsland",
                "Wet Tropics",
                "Northern Agricultural Region",
                "Peel-Harvey Region",
                "Swan Region",
                "Rangelands Region",
                "South Coast Region",
                "South West Region",
                "Marine NRM",
                "North Coast - Lord Howe Island",
                "South East NSW",
                "Adelaide and Mount Lofty Ranges",
                "Alinytjara Wilurara",
                "Burdekin",
                "Burnett Mary",
                "Cape York",
                "Co-operative Management Area",
                "East Gippsland",
                "Eyre Peninsula",
                "Fitzroy",
                "Glenelg Hopkins",
                "Port Phillip and Western Port",
                "South NRM Region",
                "South Australian Murray Darling Basin",
                "South East",
                "Corangamite",
                "North NRM Region",
                "North Coast",
                "Greater Sydney",
                "Kangaroo Island",
                "Mackay Whitsunday"
            ],
            "locality": "",
            "coordinates": [
                [
                    [
                        109.23348002808092,
                        -47.193641170803346
                    ],
                    [
                        109.23348002808092,
                        -8.883333333166718
                    ],
                    [
                        163.1920849105902,
                        -8.883333333166718
                    ],
                    [
                        163.1920849105902,
                        -47.193641170803346
                    ],
                    [
                        109.23348002808092,
                        -47.193641170803346
                    ]
                ]
            ],
            "decimalLongitude": 136.21278246933556,
            "centre": [
                "138.0822642920748",
                "-27.367263334965607"
            ],
            "aream2": 7338351717854.103,
            "decimalLatitude": -28.038487251985032,
            "pid": "9126957",
            "mvs": "",
            "uncertainty": "",
            "type": "pid",
            "name": "Prioritisation of research and management needs for Australian elasmobranch species",
            "state": [
                "Tasmania",
                "Jervis Bay Territory",
                "Queensland",
                "Victoria",
                "South Australia",
                "New South Wales",
                "Northern Territory",
                "Western Australia"
            ],
            "layerName": "User Uploaded Objects",
            "mvg": "",
            "ibra": [
                "Central Kimberley",
                "Flinders",
                "Northern Kimberley",
                "Tasmanian Northern Midlands",
                "Jarrah Forest",
                "Yalgoo",
                "South East Coastal Plain",
                "Carnarvon",
                "Mallee",
                "Gulf Plains",
                "Victoria Bonaparte",
                "Gawler",
                "Kanmantoo",
                "Naracoorte Coastal Plain",
                "Pilbara",
                "Tasmanian Southern Ranges",
                "Central Mackay Coast",
                "Sydney Basin",
                "Tasmanian Northern Slopes",
                "Dampierland",
                "Tiwi Cobourg",
                "Eyre Yorke Block",
                "Arnhem Coast",
                "Warren",
                "Gulf Coastal",
                "NSW North Coast",
                "Tasmanian West",
                "Brigalow Belt South",
                "Murray Darling Depression",
                "South East Corner",
                "South Eastern Highlands",
                "King",
                "Tasmanian South East",
                "Darwin Coastal",
                "Geraldton Sandplains",
                "Flinders Lofty Block",
                "Cape York Peninsula",
                "Brigalow Belt North",
                "Victorian Volcanic Plain",
                "Swan Coastal Plain",
                "Ben Lomond",
                "Central Arnhem",
                "Nullarbor",
                "South Eastern Queensland",
                "Wet Tropics",
                "Hampton",
                "Esperance Plains"
            ],
            "imcra4_pb": [
                "Northern Shelf Province",
                "Spencer Gulf Shelf Province",
                "Central Eastern Province",
                "Northeast Province",
                "Kenn Transition",
                "Southwest Shelf Transition",
                "West Tasmania Transition",
                "Tasmanian Shelf Province",
                "Great Australian Bight Shelf Transition",
                "Northwest Transition",
                "Cape Province",
                "Northeast Shelf Province",
                "Northwest Province",
                "Tasmania Province",
                "Central Western Shelf Transition",
                "Bass Strait Shelf Province",
                "Central Eastern Shelf Transition",
                "Kenn Province",
                "Southern Province",
                "Central Eastern Shelf Province",
                "Lord Howe Province",
                "Western Bass Strait Shelf Transition",
                "Timor Province",
                "Northeast Shelf Transition",
                "Southeast Shelf Transition",
                "Central Western Shelf Province",
                "Central Western Province",
                "Northeast Transition",
                "Southeast Transition",
                "Central Eastern Transition",
                "Timor Transition",
                "Northwest Shelf Province",
                "Southwest Shelf Province",
                "Northwest Shelf Transition",
                "Tasman Basin Province",
                "Central Western Transition",
                "Southwest Transition"
            ],
            "elect": [
                "Bonner",
                "Ryan",
                "Parramatta",
                "Bennelong",
                "Gellibrand",
                "Lalor",
                "Wannon",
                "Corio",
                "Isaacs",
                "Dunkley",
                "Holt",
                "Monash",
                "O'Connor",
                "Forrest",
                "Kingston",
                "North Sydney",
                "Kingsford Smith",
                "Whitlam",
                "Gilmore",
                "Lyne",
                "Eden-Monaro",
                "Reid",
                "Bass",
                "Franklin",
                "Flinders",
                "Lyons",
                "Clark",
                "Macnamara",
                "Corangamite",
                "Bowman",
                "Oxley",
                "Moreton",
                "Moncrieff",
                "Mcpherson",
                "Spence",
                "Hindmarsh",
                "Makin",
                "Boothby",
                "Fisher",
                "Fairfax",
                "Longman",
                "Mayo",
                "Warringah",
                "Cunningham",
                "Kennedy",
                "Herbert",
                "Flynn",
                "Wide Bay",
                "Hinkler",
                "Melbourne",
                "Barton",
                "Pearce",
                "Moore",
                "Stirling",
                "Curtin",
                "Swan",
                "Griffith",
                "Fadden",
                "Goldstein",
                "Cook",
                "Hughes",
                "Braddon",
                "Dawson",
                "Durack",
                "Grey",
                "Hunter",
                "Paterson",
                "Newcastle",
                "Shortland",
                "Wentworth",
                "Dobell",
                "Macquarie",
                "Robertson",
                "Berowra",
                "Mackellar",
                "Bradfield",
                "Fenner",
                "Richmond",
                "Grayndler",
                "Sydney",
                "Page",
                "Cowper",
                "Tangney",
                "Gippsland",
                "Lingiari",
                "Capricornia",
                "Solomon",
                "Leichhardt",
                "Dickson",
                "Petrie",
                "Lilley",
                "Barker",
                "Forde",
                "Brisbane",
                "Perth",
                "Fremantle",
                "Brand",
                "Canning"
            ],
            "cmz": [
                "Brigalow woodlands",
                "Eastern Australia tropical rainforests",
                "Eastern Australia temperate and subtropical forests",
                "Swan Coastal Plain shrublands and woodlands",
                "Tasman temperate forests",
                "Tasman temperate rainforests and highland forests",
                "South Eastern Australia mallee woodlands",
                "South Eastern Australia mixed temperate forests woodlands and grasslands",
                "North Australian tropical savanna woodlands",
                "Western Australian temperate sandplain woodlands",
                "Arid shrublands and desert",
                "North Eastern Australia tropical rainforests",
                "South Australian Eucalypt woodlands",
                "Esperance coastal shrublands and mallee",
                "South Western Australia temperate forests",
                "South Western Australia mallee woodlands",
                "Naracoorte woodlands"
            ],
            "other": [
                "Australian Coral Ecoregions",
                "RAMSAR wetland regions",
                "Directory of Important Wetlands",
                "NSW Local Land Services Regions",
                "Exclusive Economic Zone",
                "National Native Title Register (NNTR, Determinations of Native Title) - boundaries and core attributes",
                "Atlas of Life in the Coastal Wilderness",
                "Great Eastern Ranges Initiative",
                "Indigenous Protected Areas 2013",
                "Indigenous Land Use Agreements",
                "Areas for Further Assessment within the East Marine Region"
            ],
            "gerSubRegion": [
                "GER Border Ranges",
                "GER Illawarra to Shoalhaven",
                "GER Hunter Valley",
                "GER Jaliigirr",
                "GER Kosciuszko to Coast"
            ]
        },
        "source": "pid"
    },
    "area": 2743274.2507439414,
    "geoIndex": {
        "coordinates": [
            [
                [
                    -47.193641170803346,
                    109.23348002808092
                ],
                [
                    -8.883333333166718,
                    109.23348002808092
                ],
                [
                    -8.883333333166718,
                    163.1920849105902
                ],
                [
                    -47.193641170803346,
                    163.1920849105902
                ],
                [
                    -47.193641170803346,
                    109.23348002808092
                ]
            ]
        ],
        "type": "Polygon"
    },
};

var projects = [
    "152cfa69-317a-4327-aa9e-517ed4186c15",
    "182dde73-dc27-40f0-af7e-8b267d674d56",
    "2dcdf50d-419a-4a6a-9ade-5e5a2ace13ec",
    "3a13fd1b-e8e7-4782-8fe8-d32ffd585334",
    "4bb15e2a-130d-4889-bfe0-d6e5904660ee",
    "4c1565cc-a99f-4ed0-ac8c-766bfa8b0319",
    "4031b05a-2e24-4d07-8766-1c00855c17fc",
    "52ce5bfb-0bb0-45dd-afb1-2e7d1a85cd1a",
    "73677c8d-5c99-4523-9125-56f846d2367f",
    "e9c87d3b-9690-41b2-8b2c-afb8cb1ddee8",
    "ee724255-eabb-4dc4-9e1d-bee4b1e09bad",
    "f1d28af2-939c-416e-b898-ee34123ebb85",
    "f29fa27c-412d-4ed5-a242-709a73180ff1",
    "9826c8bc-c012-422c-8fe9-1ceeedffef08",
    "98f1f6c3-d2cb-423c-b823-de0002fe4e85",
    "9ddda723-7141-4b19-beee-61a6074f022e",
    "a3334d35-707b-4c4f-862f-bb22245dbb34",
    "b800b345-2a19-4c99-82a5-104b00339080",
    "bb024300-b374-4f44-88d7-d8b5bfb22ba7",
    "d87cab0e-3516-49d0-89a9-ced9821828de",
    "d961c817-350d-4424-bafe-177feb348cfc",
    "dd204549-d1ba-44db-9c0e-b69675224dff"
];

for (var i = 0; i < projects.length; i++) {
    var projectId = projects[i];
    var project = db.project.findOne({projectId: projectId, status: {$ne: 'deleted'}});
    if (!project) {
        print("Project with projectId: " + projectId + " not found.");
        continue;
    }

    var site = db.site.findOne({siteId: project.projectSiteId, status: {$ne: 'deleted'}});
    if(!site) {
        print("Site with siteId: " + project.projectSiteId + " not found for projectId: " + projectId);
        continue;
    }

    db.site.updateOne({siteId: site.siteId}, {$set: sitePropertiesToUpdate});
}