apply plugin:"maven-publish"
publishing {
    repositories {
        maven {
            name 'Nexus'
            url "https://nexus.ala.org.au/content/repositories/${project.version.endsWith('-SNAPSHOT') ? 'snapshots' : 'releases'}"
            credentials {
                username = System.getenv('TRAVIS_DEPLOY_USERNAME')
                password = System.getenv('TRAVIS_DEPLOY_PASSWORD')
            }
        }
    }
    publications {
        mavenJar(MavenPublication) {

            pom.withXml {
                def pomNode = asNode()
                def localPart = { node ->
                    def name = node.name()
                    name.metaClass.respondsTo(name, 'getLocalPart') ? name.localPart : name.toString()
                }
                pomNode.children().findAll { localPart(it) == 'dependencyManagement' }.each {
                    it.replaceNode {}
                }

                // simply remove dependencies without a version
                // version-less dependencies are handled with dependencyManagement
                // see https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/8 for more complete solutions
                def dependenciesNode = pomNode.children().find { localPart(it) == 'dependencies' }
                dependenciesNode?.children()?.findAll { dep ->
                    localPart(dep) == 'dependency' &&
                        !dep.children().any { child ->
                            localPart(child) == 'version' && child.text()
                        }
                }?.each { it.replaceNode {} }
            }
            artifact bootJar
        }
    }
}
