// collection: site
var siteMap =
    {
        "projects" : [],
        "siteId" : "",
        "status" : "active",
        "isSciStarter" : false,
        "extent":
            {
                "geometry":
                    {
                        "datum": "",
                        "fid": "cl1083",
                        "areaKmSq": 6967164.758167462,
                        "precision": "",
                        "lga":
                            [
                                "Singleton (A)",
                                "Cuballing (S)",
                                "Wollondilly (A)",
                                "Mitcham (C)",
                                "Buloke (S)",
                                "Kangaroo Island (Dc)",
                                "Etheridge (S)",
                                "Mansfield (S)",
                                "Rockingham (C)",
                                "Fraser Coast (R)",
                                "Loddon (S)",
                                "Tumut Shire (A)",
                                "South Burnett (R)",
                                "Yarrabah (S)",
                                "Hume (C)",
                                "Bruce Rock (S)",
                                "Bassendean (T)",
                                "Camden (A)",
                                "Glenorchy (C)",
                                "Strathbogie (S)",
                                "Rockdale (C)",
                                "Dardanup (S)",
                                "Narrandera (A)",
                                "Cooma-Monaro (A)",
                                "Dundas (S)",
                                "Devonport (C)",
                                "Narromine (A)",
                                "Dubbo (C)",
                                "Franklin Harbour (Dc)",
                                "Grant (Dc)",
                                "Plantagenet (S)",
                                "Donnybrook-Balingup (S)",
                                "Ku-Ring-Gai (A)",
                                "Kowanyama (S)",
                                "Lismore (C)",
                                "Kingston (Dc)",
                                "Macedon Ranges (S)",
                                "Nedlands (C)",
                                "Fairfield (C)",
                                "Gold Coast (C)",
                                "Brimbank (C)",
                                "Tablelands (R)",
                                "Richmond (S)",
                                "Parramatta (C)",
                                "Bunbury (C)",
                                "Katherine (T)",
                                "Jerramungup (S)",
                                "Belyuen (S)",
                                "Port Lincoln (C)",
                                "South Gippsland (S)",
                                "Bega Valley (A)",
                                "Belmont (C)",
                                "Kogarah (C)",
                                "Wandering (S)",
                                "Northern Grampians (S)",
                                "Whitehorse (C)",
                                "Waratah/Wynyard (M)",
                                "Walgett (A)",
                                "Upper Hunter Shire (A)",
                                "Unincorporated Vic",
                                "Yorke Peninsula (Dc)",
                                "Yarra Ranges (S)",
                                "Yankalilla (Dc)",
                                "Carnamah (S)",
                                "Berrigan (A)",
                                "Fremantle (C)",
                                "West Torrens (C)",
                                "Wellington (S)",
                                "Mid Murray (Dc)",
                                "Uralla (A)",
                                "Kempsey (A)",
                                "Mount Isa (C)",
                                "Alexandrina (Dc)",
                                "Gympie (R)",
                                "Roper Gulf (S)",
                                "Kingston (C)",
                                "Greater Dandenong (C)",
                                "Central Coast (M)",
                                "Kiama (A)",
                                "Flinders (S)",
                                "Mackay (R)",
                                "Boorowa (A)",
                                "Shark Bay (S)",
                                "Wakool (A)",
                                "Hawkesbury (C)",
                                "Corowa Shire (A)",
                                "Junee (A)",
                                "Cranbrook (S)",
                                "Young (A)",
                                "Orange (C)",
                                "North Sydney (A)",
                                "Richmond Valley (A)",
                                "Mundaring (S)",
                                "Kyogle (A)",
                                "Melville (C)",
                                "Moorabool (S)",
                                "Mildura (Rc)",
                                "Botany Bay (C)",
                                "Boyup Brook (S)",
                                "Boddington (S)",
                                "Bombala (A)",
                                "Latrobe (C)",
                                "East Arnhem (S)",
                                "Barunga West (Dc)",
                                "Cabonne (A)",
                                "Canada Bay (A)",
                                "Griffith (C)",
                                "Hurstville (C)",
                                "Kentish (M)",
                                "Sutherland Shire (A)",
                                "Surf Coast (S)",
                                "Cambridge (T)",
                                "Whittlesea (C)",
                                "Victoria-Daly (S)",
                                "Carpentaria (S)",
                                "Yarra (C)",
                                "Blacktown (C)",
                                "Wyong (A)",
                                "Mallala (Dc)",
                                "Dorset (M)",
                                "Robe (Dc)",
                                "North Burnett (R)",
                                "Northern Midlands (M)",
                                "Whitsunday (R)",
                                "Wangaratta (Rc)",
                                "Unincorporated Nt",
                                "Chapman Valley (S)",
                                "Central Goldfields (S)",
                                "Central Highlands (R)",
                                "Central Highlands (M)",
                                "Waroona (S)",
                                "Great Lakes (A)",
                                "Gladstone (R)",
                                "Campbelltown (C) (Sa)",
                                "Campbelltown (C) (Act)",
                                "Glamorgan/Spring Bay (M)",
                                "Pittwater (A)",
                                "Weddin (A)",
                                "Barcoo (S)",
                                "Gloucester (A)",
                                "Goondiwindi (R)",
                                "Brighton (M)",
                                "Brisbane (C)",
                                "Croydon (S)",
                                "Cowra (A)",
                                "Sunshine Coast (R)",
                                "Tenterfield (A)",
                                "Tamworth Regional (A)",
                                "Tasman (M)",
                                "Roebourne (S)",
                                "Greater Geelong (C)",
                                "Wollongong (C)",
                                "Wodonga (Rc)",
                                "Alpine (S)",
                                "Northern Peninsula Area (R)",
                                "Snowy River (A)",
                                "Salisbury (C)",
                                "Lake Grace (S)",
                                "Moonee Valley (C)",
                                "Meekatharra (S)",
                                "Derwent Valley (M)",
                                "Quilpie (S)",
                                "Queanbeyan (C)",
                                "Penrith (C)",
                                "Mount Alexander (S)",
                                "Yarriambiack (S)",
                                "Central Darling (A)",
                                "Parkes (A)",
                                "Napranum (S)",
                                "Nambucca (A)",
                                "Narrabri (A)",
                                "Muswellbrook (A)",
                                "Nannup (S)",
                                "Murray Bridge (Rc)",
                                "Walcha (A)",
                                "Coolamon (A)",
                                "Unincorporated Act",
                                "Charters Towers (R)",
                                "Circular Head (M)",
                                "Lane Cove (A)",
                                "Capel (S)",
                                "Frankston (C)",
                                "Darebin (C)",
                                "Murray (A)",
                                "Yass Valley (A)",
                                "Coonamble (A)",
                                "Corangamite (S)",
                                "Ngaanyatjarraku (S)",
                                "Onkaparinga (C)",
                                "Murrindindi (S)",
                                "Cunderdin (S)",
                                "Kalgoorlie/Boulder (C)",
                                "Orroroo/Carrieton (Dc)",
                                "Logan (C)",
                                "Flinders (M)",
                                "Coorow (S)",
                                "Monash (C)",
                                "Gosford (C)",
                                "Adelaide Hills (Dc)",
                                "Greater Taree (C)",
                                "Gingin (S)",
                                "Lithgow (C)",
                                "Denmark (S)",
                                "Campaspe (S)",
                                "Glen Innes Severn (A)",
                                "Koorda (S)",
                                "Mount Barker (Dc)",
                                "Woodanilling (S)",
                                "Scenic Rim (R)",
                                "Wentworth (A)",
                                "Broomehill-Tambellup (S)",
                                "Burnie (C)",
                                "Bayswater (C)",
                                "Bayside (C)",
                                "Hepburn (S)",
                                "Launceston (C)",
                                "Liverpool (C)",
                                "Albury (C)",
                                "Mid-Western Regional (A)",
                                "Mitchell (S)",
                                "Woorabinda (S)",
                                "Gosnells (C)",
                                "Unley (C)",
                                "Toodyay (S)",
                                "West Arthur (S)",
                                "Mount Gambier (C)",
                                "Kimba (Dc)",
                                "Leonora (S)",
                                "Broken Hill (C)",
                                "Maralinga Tjarutja (Ac)",
                                "Claremont (T)",
                                "Menzies (S)",
                                "Goomalling (S)",
                                "East Fremantle (T)",
                                "Lockhart River (S)",
                                "Torres (S)",
                                "Bland (A)",
                                "Gawler (T)",
                                "Narrogin (T)",
                                "Coober Pedy (Dc)",
                                "Alice Springs (T)",
                                "Wongan-Ballidu (S)",
                                "Roxby Downs (M)",
                                "Trayning (S)",
                                "Inverell (A)",
                                "Hope Vale (S)",
                                "Holroyd (C)",
                                "Waverley (A)",
                                "Boulia (S)",
                                "Murchison (S)",
                                "Mukinbudin (S)",
                                "Lower Eyre Peninsula (Dc)",
                                "Irwin (S)",
                                "Isaac (R)",
                                "Kalamunda (S)",
                                "Jerilderie (A)",
                                "Ipswich (C)",
                                "Holdfast Bay (C)",
                                "Hindmarsh (S)",
                                "Hobart (C)",
                                "Hornsby (A)",
                                "Glen Eira (C)",
                                "Cottesloe (T)",
                                "Kondinin (S)",
                                "Burnside (C)",
                                "Baw Baw (S)",
                                "Bathurst Regional (A)",
                                "Mount Magnet (S)",
                                "Mount Marshall (S)",
                                "Marion (C)",
                                "Maribyrnong (C)",
                                "Maroondah (C)",
                                "Mapoon (S)",
                                "Manningham (C)",
                                "Maitland (C)",
                                "Mandurah (C)",
                                "Macdonnell (S)",
                                "Elliston (Dc)",
                                "Esperance (S)",
                                "Eurobodalla (A)",
                                "Doomadgee (S)",
                                "Diamantina (S)",
                                "Burwood (A)",
                                "Hay (A)",
                                "Morawa (S)",
                                "Lockyer Valley (R)",
                                "Indigo (S)",
                                "Deniliquin (A)",
                                "Winton (S)",
                                "Queenscliffe (B)",
                                "Stonnington (C)",
                                "Cootamundra (A)",
                                "Sydney (C)",
                                "Southern Midlands (M)",
                                "Warringah (A)",
                                "Wattle Range (Dc)",
                                "Warrumbungle Shire (A)",
                                "Ravensthorpe (S)",
                                "Redland (C)",
                                "Port Stephens (A)",
                                "Port Augusta (C)",
                                "Port Hedland (T)",
                                "Port Adelaide Enfield (C)",
                                "Pormpuraaw (S)",
                                "Playford (C)",
                                "Pyrenees (S)",
                                "Port Macquarie-Hastings (A)",
                                "Prospect (C)",
                                "Port Phillip (C)",
                                "Port Pirie City And Dists (M)",
                                "Peppermint Grove (S)",
                                "Perenjori (S)",
                                "Wagait (S)",
                                "Paroo (S)",
                                "Narembeen (S)",
                                "Naracoorte And Lucindale (Dc)",
                                "Weipa (T)",
                                "Warrnambool (C)",
                                "Murrumbidgee (A)",
                                "Bankstown (C)",
                                "Banana (S)",
                                "Aurukun (S)",
                                "Ballarat (C)",
                                "Murray (S)",
                                "Balonne (S)",
                                "Ballina (A)",
                                "Balranald (A)",
                                "Walkerville (M)",
                                "Wakefield (Dc)",
                                "Anangu Pitjantjatjara (Ac)",
                                "Ararat (Rc)",
                                "Victoria Plains (S)",
                                "Vincent (T)",
                                "Upper Gascoyne (S)",
                                "Upper Lachlan Shire (A)",
                                "Unincorporated Nsw",
                                "Unincorporated Sa",
                                "Tumby Bay (Dc)",
                                "Tweed (A)",
                                "Unincorp. Other Territories",
                                "Towong (S)",
                                "Townsville (C)",
                                "Tumbarumba (A)",
                                "The Hills Shire (A)",
                                "Ashfield (A)",
                                "Adelaide (C)",
                                "Ashburton (S)",
                                "Armidale Dumaresq (A)",
                                "Augusta-Margaret River (S)",
                                "Albany (C)",
                                "Tatiara (Dc)",
                                "Tammin (S)",
                                "Cloncurry (S)",
                                "Cockburn (C)",
                                "Cobar (A)",
                                "Colac-Otway (S)",
                                "Coffs Harbour (C)",
                                "Clarence Valley (A)",
                                "Clarence (C)",
                                "Clare And Gilbert Valleys (Dc)",
                                "Chittering (S)",
                                "Cherbourg (S)",
                                "Central Desert (S)",
                                "Williams (S)",
                                "Mosman Park (T)",
                                "Moora (S)",
                                "Armadale (C)",
                                "Horsham (Rc)",
                                "Palmerston (C)",
                                "Sandstone (S)",
                                "Barkly (S)",
                                "Westonia (S)",
                                "Wujal Wujal (S)",
                                "Peterborough (Dc)",
                                "Wanneroo (C)",
                                "Warren (A)",
                                "Wagga Wagga (C)",
                                "The Coorong (Dc)",
                                "Stirling (C)",
                                "Southern Mallee (Dc)",
                                "Somerset (R)",
                                "Serpentine-Jarrahdale (S)",
                                "Collie (S)",
                                "Cleve (Dc)",
                                "Cassowary Coast (R)",
                                "Casey (C)",
                                "West Arnhem (S)",
                                "Yilgarn (S)",
                                "Wickepin (S)",
                                "Dumbleyung (S)",
                                "Forbes (A)",
                                "Katanning (S)",
                                "Coolgardie (S)",
                                "Gundagai (A)",
                                "Cue (S)",
                                "Mingenew (S)",
                                "Wudinna (Dc)",
                                "Bulloo (S)",
                                "York (S)",
                                "Corrigin (S)",
                                "Strathfield (A)",
                                "Leeton (A)",
                                "Lake Macquarie (C)",
                                "Gunnedah (A)",
                                "Guyra (A)",
                                "Melton (S)",
                                "Hobsons Bay (C)",
                                "Hinchinbrook (S)",
                                "Dowerin (S)",
                                "Dungog (A)",
                                "Dalwallinu (S)",
                                "Dandaragan (S)",
                                "Laverton (S)",
                                "Flinders Ranges (Dc)",
                                "Lachlan (A)",
                                "Northam (S)",
                                "Derby-West Kimberley (S)",
                                "Gilgandra (A)",
                                "Beverley (S)",
                                "Charles Sturt (C)",
                                "Northampton (S)",
                                "Gnowangerup (S)",
                                "East Gippsland (S)",
                                "Nungarin (S)",
                                "Wingecarribee (A)",
                                "Tea Tree Gully (C)",
                                "Mullewa (S)",
                                "King Island (M)",
                                "Kingborough (M)",
                                "Kent (S)",
                                "Joondalup (C)",
                                "Wyndham (C)",
                                "South Perth (C)",
                                "Moreland (C)",
                                "Merredin (S)",
                                "Moree Plains (A)",
                                "Gannawarra (S)",
                                "Moira (S)",
                                "Greater Shepparton (C)",
                                "Hunters Hill (A)",
                                "Halls Creek (S)",
                                "Victor Harbor (C)",
                                "Wagin (S)",
                                "Shellharbour (C)",
                                "Carrathool (A)",
                                "Litchfield (M)",
                                "Liverpool Plains (A)",
                                "Longreach (R)",
                                "Mosman (A)",
                                "Quairading (S)",
                                "Western Downs (R)",
                                "Burdekin (S)",
                                "Narrogin (S)",
                                "Murweh (S)",
                                "Moyne (S)",
                                "Geraldton-Greenough (C)",
                                "Kojonup (S)",
                                "Goyder (Dc)",
                                "Goulburn Mulwaree (A)",
                                "George Town (M)",
                                "Glenelg (S)",
                                "Benalla (Rc)",
                                "Melbourne (C)",
                                "Newcastle (C)",
                                "Boroondara (C)",
                                "Mount Remarkable (Dc)",
                                "Moreton Bay (R)",
                                "Broome (S)",
                                "Subiaco (C)",
                                "Urana (A)",
                                "Whyalla (C)",
                                "Blackall Tambo (R)",
                                "Bundaberg (R)",
                                "Burke (S)",
                                "Brookton (S)",
                                "Karoonda East Murray (Dc)",
                                "Yalgoo (S)",
                                "Exmouth (S)",
                                "West Wimmera (S)",
                                "Kellerberrin (S)",
                                "Manjimup (S)",
                                "Three Springs (S)",
                                "Toowoomba (R)",
                                "West Tamar (M)",
                                "Busselton (S)",
                                "Loxton Waikerie (Dc)",
                                "Gwydir (A)",
                                "Greater Bendigo (C)",
                                "East Pilbara (S)",
                                "Bourke (A)",
                                "Brewarrina (A)",
                                "Break O'Day (M)",
                                "Swan Hill (Rc)",
                                "Byron (A)",
                                "Temora (A)",
                                "Streaky Bay (Dc)",
                                "Berri And Barmera (Dc)",
                                "Meander Valley (M)",
                                "Southern Grampians (S)",
                                "Shoalhaven (C)",
                                "Auburn (C)",
                                "Conargo (A)",
                                "Kulin (S)",
                                "Kwinana (T)",
                                "Wyalkatchem (S)",
                                "Ceduna (Dc)",
                                "Rockhampton (R)",
                                "Renmark Paringa (Dc)",
                                "Randwick (C)",
                                "Nillumbik (S)",
                                "Victoria Park (T)",
                                "Cessnock (C)",
                                "Willoughby (C)",
                                "Wellington (A)",
                                "Canterbury (C)",
                                "Swan (C)",
                                "Palerang (A)",
                                "Sorell (M)",
                                "Cook (S)",
                                "West Coast (M)",
                                "Wiluna (S)",
                                "Copper Coast (Dc)",
                                "Coomalie (S)",
                                "Lockhart (A)",
                                "Marrickville (A)",
                                "Mckinlay (S)",
                                "Harvey (S)",
                                "Cardinia (S)",
                                "Perth (C)",
                                "Darwin (C)",
                                "Norwood Payneham St Peters (C)",
                                "Wyndham-East Kimberley (S)",
                                "Southern Downs (R)",
                                "Northern Areas (Dc)",
                                "Woollahra (A)",
                                "Oberon (A)",
                                "Carnarvon (S)",
                                "Harden (A)",
                                "Bellingen (A)",
                                "Huon Valley (M)",
                                "Canning (C)",
                                "Bogan (A)",
                                "Blayney (A)",
                                "Blue Mountains (C)",
                                "Latrobe (M)",
                                "Light (Regc)",
                                "Leichhardt (A)",
                                "Barcaldine (R)",
                                "Barossa (Dc)",
                                "Bass Coast (S)",
                                "Banyule (C)",
                                "Bridgetown-Greenbushes (S)",
                                "Tiwi Islands (S)",
                                "Golden Plains (S)",
                                "Cairns (R)",
                                "Greater Hume Shire (A)",
                                "Pingelly (S)",
                                "Maranoa (R)",
                                "Manly (A)",
                                "Knox (C)",
                                "Ryde (C)",
                                "Mornington Peninsula (S)"
                            ],
                        "bbox": "POLYGON((113.225997779374 -43.5699998116991,113.225997779374 -10.6870001934595,153.623992688912 -10.6870001934595,153.623992688912 -43.5699998116991,113.225997779374 -43.5699998116991))",
                        "nrm":
                            [
                                "Murray",
                                "North West Nsw",
                                "Northern Tablelands",
                                "Riverina",
                                "Western",
                                "Greater Sydney",
                                "Hunter",
                                "North Coast",
                                "South East Nsw",
                                "Wimmera",
                                "Corangamite",
                                "East Gippsland",
                                "Glenelg Hopkins",
                                "Port Phillip And Western Port",
                                "West Gippsland",
                                "Avon River Basin",
                                "Northern Agricultural Region",
                                "Peel-Harvey Region",
                                "Swan Region",
                                "Act",
                                "Marine Nrm",
                                "Central Tablelands",
                                "Central West",
                                "Northern Territory",
                                "Condamine",
                                "Desert Channels",
                                "Maranoa Balonne And Border Rivers",
                                "South West Queensland",
                                "Burnett Mary",
                                "Cape York",
                                "Co-Operative Management Area",
                                "Rangelands Region",
                                "South Coast Region",
                                "South West Region",
                                "Fitzroy",
                                "Burdekin",
                                "Northern Gulf",
                                "Mackay Whitsunday",
                                "South East Queensland",
                                "Southern Gulf",
                                "Wet Tropics",
                                "Torres Strait",
                                "South Australian Murray Darling Basin",
                                "Alinytjara Wilurara",
                                "Eyre Peninsula",
                                "Green Adelaide",
                                "Hills And Fleurieu",
                                "Kangaroo Island",
                                "Limestone Coast",
                                "Northern And Yorke",
                                "South Australian Arid Lands",
                                "North West Nrm Region",
                                "North Nrm Region",
                                "South Nrm Region",
                                "Goulburn Broken",
                                "Mallee",
                                "North Central",
                                "North East"
                            ],
                        "locality": "",
                        "coordinates":
                            [
                                [
                                    [
                                        113.225997779374,
                                        -43.5699998116991
                                    ],
                                    [
                                        113.225997779374,
                                        -10.6870001934595
                                    ],
                                    [
                                        153.623992688912,
                                        -10.6870001934595
                                    ],
                                    [
                                        153.623992688912,
                                        -43.5699998116991
                                    ],
                                    [
                                        113.225997779374,
                                        -43.5699998116991
                                    ]
                                ]
                            ],
                        "decimalLongitude": 133.424995234143,
                        "centre":
                            [
                                "134.48225543571928",
                                "-25.7189592999083"
                            ],
                        "aream2": 7870871728950.685,
                        "decimalLatitude": -27.1285000025793,
                        "pid": "8943234",
                        "mvs": "",
                        "uncertainty": "",
                        "type": "pid",
                        "name": "Site 2",
                        "state":
                            [
                                "Tasmania",
                                "Queensland",
                                "Victoria",
                                "South Australia",
                                "New South Wales",
                                "Northern Territory",
                                "Western Australia",
                                "Australian Capital Territory"
                            ],
                        "layerName": "User Uploaded Objects",
                        "mvg": "",
                        "ibra":
                            [
                                "Central Kimberley",
                                "Little Sandy Desert",
                                "Darling Riverine Plains",
                                "Einasleigh Uplands",
                                "Avon Wheatbelt",
                                "Flinders",
                                "Northern Kimberley",
                                "Tasmanian Northern Midlands",
                                "Jarrah Forest",
                                "Nsw South Western Slopes",
                                "Yalgoo",
                                "South East Coastal Plain",
                                "Broken Hill Complex",
                                "Victoria Bonaparte",
                                "Gawler",
                                "Kanmantoo",
                                "Tasmanian Central Highlands",
                                "Carnarvon",
                                "Mallee",
                                "New England Tablelands",
                                "Gulf Plains",
                                "Naracoorte Coastal Plain",
                                "Pilbara",
                                "Tanami",
                                "Gulf Fall And Uplands",
                                "Tasmanian Southern Ranges",
                                "Riverina",
                                "Ord Victoria Plain",
                                "Central Mackay Coast",
                                "Murchison",
                                "Desert Uplands",
                                "Sydney Basin",
                                "Australian Alps",
                                "Tasmanian Northern Slopes",
                                "Dampierland",
                                "Tiwi Cobourg",
                                "Eyre Yorke Block",
                                "Arnhem Coast",
                                "Warren",
                                "Stony Plains",
                                "Channel Country",
                                "Gulf Coastal",
                                "Nandewar",
                                "Great Sandy Desert",
                                "Mulga Lands",
                                "Nsw North Coast",
                                "Tasmanian West",
                                "Brigalow Belt South",
                                "Murray Darling Depression",
                                "Mitchell Grass Downs",
                                "South East Corner",
                                "South Eastern Highlands",
                                "Central Ranges",
                                "King",
                                "Davenport Murchison Ranges",
                                "Tasmanian South East",
                                "Darwin Coastal",
                                "Geraldton Sandplains",
                                "Mount Isa Inlier",
                                "Macdonnell Ranges",
                                "Flinders Lofty Block",
                                "Gibson Desert",
                                "Cape York Peninsula",
                                "Great Victoria Desert",
                                "Cobar Peneplain",
                                "Victorian Midlands",
                                "Finke",
                                "Brigalow Belt North",
                                "Victorian Volcanic Plain",
                                "Gascoyne",
                                "Simpson Strzelecki Dunefields",
                                "Swan Coastal Plain",
                                "Sturt Plateau",
                                "Daly Basin",
                                "Ben Lomond",
                                "Arnhem Plateau",
                                "Pine Creek",
                                "Coolgardie",
                                "Central Arnhem",
                                "Nullarbor",
                                "South Eastern Queensland",
                                "Wet Tropics",
                                "Hampton",
                                "Burt Plain",
                                "Esperance Plains"
                            ],
                        "imcra4_pb":
                            [
                                "Northern Shelf Province",
                                "Spencer Gulf Shelf Province",
                                "Southwest Shelf Transition",
                                "Tasmanian Shelf Province",
                                "Great Australian Bight Shelf Transition",
                                "Northeast Shelf Province",
                                "Central Western Shelf Transition",
                                "Bass Strait Shelf Province",
                                "Central Eastern Shelf Transition",
                                "Central Eastern Shelf Province",
                                "Western Bass Strait Shelf Transition",
                                "Northeast Shelf Transition",
                                "Southeast Shelf Transition",
                                "Central Western Shelf Province",
                                "Northwest Shelf Province",
                                "Southwest Shelf Province",
                                "Northwest Shelf Transition"
                            ],
                        "elect":
                            [
                                "Aston",
                                "Ballarat",
                                "Bendigo",
                                "Bruce",
                                "Calwell",
                                "Casey",
                                "Chisholm",
                                "Cooper",
                                "Corangamite",
                                "Corio",
                                "Deakin",
                                "Dunkley",
                                "Flinders",
                                "Gellibrand",
                                "Gippsland",
                                "Indi",
                                "Isaacs",
                                "Jagajaga",
                                "Kooyong",
                                "La Trobe",
                                "Lalor",
                                "Mallee",
                                "Maribyrnong",
                                "Mcewen",
                                "Melbourne",
                                "Menzies",
                                "Monash",
                                "Nicholls",
                                "Scullin",
                                "Wannon",
                                "Wills",
                                "Berowra",
                                "Blaxland",
                                "Calare",
                                "Chifley",
                                "Cowper",
                                "Cunningham",
                                "Dobell",
                                "Eden-Monaro",
                                "Farrer",
                                "Fowler",
                                "Gilmore",
                                "Grayndler",
                                "Greenway",
                                "Hughes",
                                "Hume",
                                "Hunter",
                                "Lindsay",
                                "Lyne",
                                "Macarthur",
                                "Mackellar",
                                "Macquarie",
                                "Mcmahon",
                                "Mitchell",
                                "New England",
                                "Newcastle",
                                "Page",
                                "Parkes",
                                "Paterson",
                                "Reid",
                                "Richmond",
                                "Riverina",
                                "Robertson",
                                "Shortland",
                                "Watson",
                                "Werriwa",
                                "Whitlam",
                                "Brand",
                                "Bullwinkel",
                                "Burt",
                                "Canning",
                                "Cowan",
                                "Curtin",
                                "Durack",
                                "Forrest",
                                "Fremantle",
                                "Hasluck",
                                "Moore",
                                "O'Connor",
                                "Pearce",
                                "Perth",
                                "Swan",
                                "Tangney",
                                "Bass",
                                "Braddon",
                                "Clark",
                                "Franklin",
                                "Lyons",
                                "Adelaide",
                                "Barker",
                                "Boothby",
                                "Grey",
                                "Kingston",
                                "Makin",
                                "Mayo",
                                "Spence",
                                "Sturt",
                                "Blair",
                                "Bonner",
                                "Bowman",
                                "Brisbane",
                                "Capricornia",
                                "Dawson",
                                "Dickson",
                                "Fadden",
                                "Fairfax",
                                "Fisher",
                                "Flynn",
                                "Forde",
                                "Petrie",
                                "Rankin",
                                "Ryan",
                                "Wide Bay",
                                "Wright",
                                "Lingiari",
                                "Solomon",
                                "Bean",
                                "Canberra",
                                "Fenner",
                                "Gorton",
                                "Hawke",
                                "Holt",
                                "Hotham",
                                "Griffith",
                                "Groom",
                                "Herbert",
                                "Hinkler",
                                "Kennedy",
                                "Leichhardt",
                                "Lilley",
                                "Longman",
                                "Maranoa",
                                "Mcpherson",
                                "Moncrieff",
                                "Moreton",
                                "Oxley"
                            ],
                        "cmz":
                            [
                                "South Western Australia Temperate Woodlands",
                                "Brigalow Woodlands",
                                "Eastern Australia Tropical Rainforests",
                                "Eastern Australia Woodlands",
                                "Eastern Australia Temperate And Subtropical Forests",
                                "Swan Coastal Plain Shrublands And Woodlands",
                                "Tasman Temperate Forests",
                                "Tasman Temperate Rainforests And Highland Forests",
                                "South Eastern Australia Mallee Woodlands",
                                "South Eastern Australia Mixed Temperate Forests Woodlands And Grasslands",
                                "Mitchell Grasslands",
                                "North Australian Tropical Savanna Woodlands",
                                "Western Australian Temperate Sandplain Woodlands",
                                "Arid Shrublands And Desert",
                                "North Eastern Australia Tropical Rainforests",
                                "South Australian Eucalypt Woodlands",
                                "Esperance Coastal Shrublands And Mallee",
                                "South Eastern Australia Temperate Woodlands",
                                "Australian Alps Montane Grasslands And Heathlands",
                                "South Western Australia Temperate Forests",
                                "South Western Australia Mallee Woodlands",
                                "Naracoorte Woodlands",
                                "Eastern Australia Mulga Shrublands"
                            ],
                        "other":
                            [
                                "Australian Coral Ecoregions",
                                "Ramsar Wetland Regions",
                                "Directory Of Important Wetlands",
                                "Act Tams Reserves",
                                "Nsw Local Land Services Regions",
                                "National Native Title Register (Nntr, Determinations Of Native Title) - Boundaries And Core Attributes",
                                "Atlas Of Life In The Coastal Wilderness",
                                "Great Eastern Ranges Initiative",
                                "Indigenous Protected Areas 2013",
                                "Indigenous Land Use Agreements"
                            ],
                        "gerSubRegion":
                            [
                                "Ger Border Ranges",
                                "Ger Illawarra To Shoalhaven",
                                "Ger Southern Highlands",
                                "Ger Hunter Valley",
                                "Ger Jaliigirr",
                                "Ger Central Victorial Biolinks",
                                "Ger Kosciuszko To Coast",
                                "Ger Slopes To Summit",
                                "Ger Victorian Biolinks"
                            ],
                        "intersectionAreaByFacets":
                            {
                                "state":
                                    {
                                        "CURRENT":
                                            {
                                                "Tasmania": 66869330329.30252,
                                                "Queensland": 1735639346629.2236,
                                                "Victoria": 225842600812.9477,
                                                "South Australia": 983888448008.3287,
                                                "New South Wales": 800842021977.7275,
                                                "Northern Territory": 1348158626335.4941,
                                                "Western Australia": 2533780633018.248,
                                                "Australian Capital Territory": 2358170668.815039
                                            },
                                        "cl927":
                                            {
                                                "Tasmania": 66869330329.30252,
                                                "Queensland": 1735639346629.2236,
                                                "Victoria": 225842600812.9477,
                                                "South Australia": 983888448008.3287,
                                                "New South Wales": 800842021977.7275,
                                                "Northern Territory": 1348158626335.4941,
                                                "Western Australia": 2533780633018.248,
                                                "Australian Capital Territory": 2358170668.815039
                                            }
                                    },
                                "elect":
                                    {
                                        "CURRENT":
                                            {
                                                "Aston": 123723650.98539223,
                                                "Ballarat": 5327230073.755006,
                                                "Bendigo": 6181179215.908792,
                                                "Bruce": 141606582.83870196,
                                                "Calwell": 190975814.2516695,
                                                "Casey": 2622676559.5893054,
                                                "Chisholm": 72753136.99542378,
                                                "Cooper": 61076488.86062691,
                                                "Corangamite": 577484449.44329,
                                                "Corio": 1168250929.5904396,
                                                "Deakin": 98325604.6393313,
                                                "Dunkley": 147768707.82965586,
                                                "Flinders": 628407176.8840953,
                                                "Gellibrand": 123127339.41818021,
                                                "Gippsland": 31954278842.762264,
                                                "Indi": 29168879581.278713,
                                                "Isaacs": 157743264.12605038,
                                                "Jagajaga": 137199575.01616597,
                                                "Kooyong": 59047063.164501056,
                                                "La Trobe": 1301951577.2203968,
                                                "Lalor": 175839798.9325303,
                                                "Mallee": 83390266014.52559,
                                                "Maribyrnong": 69888492.74177569,
                                                "Mcewen": 2288080225.3816295,
                                                "Melbourne": 39415531.29949789,
                                                "Menzies": 102131932.99025893,
                                                "Monash": 7833516784.431833,
                                                "Nicholls": 14114121837.121017,
                                                "Scullin": 173756723.3666137,
                                                "Wannon": 33565794702.612484,
                                                "Wills": 47111858.12994569,
                                                "Berowra": 756607218.8533256,
                                                "Blaxland": 59317411.68302002,
                                                "Calare": 32666723567.545666,
                                                "Chifley": 112707173.50006439,
                                                "Cowper": 7110762007.412807,
                                                "Cunningham": 496420418.4417343,
                                                "Dobell": 680849013.5861458,
                                                "Eden-Monaro": 31704242672.037907,
                                                "Farrer": 126698419963.51266,
                                                "Fowler": 62488477.01084343,
                                                "Gilmore": 6104579732.541229,
                                                "Grayndler": 34191320.77703141,
                                                "Greenway": 89579116.04513085,
                                                "Hughes": 357624639.8560632,
                                                "Hume": 2675346393.11572,
                                                "Hunter": 7242521263.439364,
                                                "Lindsay": 325218946.37201685,
                                                "Lyne": 15780182798.569221,
                                                "Macarthur": 306913986.40165627,
                                                "Mackellar": 208543031.13319728,
                                                "Macquarie": 4388915863.543869,
                                                "Mcmahon": 178562818.50641376,
                                                "Mitchell": 79283461.94634277,
                                                "New England": 75238849573.32271,
                                                "Newcastle": 136600396.05090922,
                                                "Page": 19230662247.062187,
                                                "Parkes": 407228254718.4335,
                                                "Paterson": 831835912.1305839,
                                                "Reid": 55081311.55810036,
                                                "Richmond": 2068432794.1779742,
                                                "Riverina": 52390906267.30796,
                                                "Robertson": 846734094.9512271,
                                                "Shortland": 150152969.19126356,
                                                "Watson": 50487818.802329645,
                                                "Werriwa": 110958350.76545186,
                                                "Whitlam": 3016763609.0392923,
                                                "Brand": 294283954.88537806,
                                                "Bullwinkel": 9500587811.944223,
                                                "Burt": 221698823.98321843,
                                                "Canning": 3718647111.700034,
                                                "Cowan": 107587716.38052757,
                                                "Curtin": 101611204.04251982,
                                                "Durack": 1411972193630.463,
                                                "Forrest": 6332282915.240249,
                                                "Fremantle": 166544621.3065567,
                                                "Hasluck": 258208922.04810125,
                                                "Moore": 101909819.288829,
                                                "O'Connor": 1092820212525.3754,
                                                "Pearce": 739450341.4003032,
                                                "Perth": 73456054.2608656,
                                                "Swan": 133011882.95798391,
                                                "Tangney": 107233999.38372006,
                                                "Bass": 7133844413.857011,
                                                "Braddon": 20650223436.39441,
                                                "Clark": 287567847.90811396,
                                                "Franklin": 5248103537.254256,
                                                "Lyons": 31465891509.9013,
                                                "Adelaide": 86494355.4000915,
                                                "Barker": 64378134015.46753,
                                                "Boothby": 107289439.0427778,
                                                "Grey": 907727441456.8156,
                                                "Kingston": 132919535.54232599,
                                                "Makin": 162408301.99221212,
                                                "Mayo": 8462853770.491209,
                                                "Spence": 501095423.6743442,
                                                "Sturt": 97700384.70947312,
                                                "Blair": 6466687014.306615,
                                                "Bonner": 183375799.29930827,
                                                "Bowman": 275029867.29490465,
                                                "Brisbane": 57435389.10985921,
                                                "Capricornia": 90716365878.26007,
                                                "Dawson": 14702849883.281992,
                                                "Dickson": 723758721.2266728,
                                                "Fadden": 383400916.1013847,
                                                "Fairfax": 991897837.2399374,
                                                "Fisher": 1155173092.759791,
                                                "Flynn": 132187430513.48091,
                                                "Forde": 417269732.48769313,
                                                "Petrie": 129191081.47938274,
                                                "Rankin": 130940116.94156869,
                                                "Ryan": 370220989.8569052,
                                                "Wide Bay": 13975568219.639923,
                                                "Wright": 7571534363.860414,
                                                "Lingiari": 1343355888276.2444,
                                                "Solomon": 181966697.25652018,
                                                "Bean": 1874986548.1752708,
                                                "Canberra": 312315193.6282977,
                                                "Fenner": 187782146.388916,
                                                "Gorton": 207466704.81595242,
                                                "Hawke": 1986679675.458412,
                                                "Holt": 214262158.19647476,
                                                "Hotham": 81003918.94249208,
                                                "Griffith": 57329779.201792866,
                                                "Groom": 5583628147.2836485,
                                                "Herbert": 1064450601.7249672,
                                                "Hinkler": 3824702080.70752,
                                                "Kennedy": 567094492150.0691,
                                                "Leichhardt": 148928783884.08304,
                                                "Lilley": 140758680.7815742,
                                                "Longman": 1100782952.691666,
                                                "Maranoa": 732248042092.8848,
                                                "Mcpherson": 217013594.53176102,
                                                "Moncrieff": 103418959.46132593,
                                                "Moreton": 109489014.90769486,
                                                "Oxley": 158417403.85699183
                                            },
                                        "cl11225":
                                            {
                                                "Aston": 123723650.98539223,
                                                "Ballarat": 5327230073.755006,
                                                "Bendigo": 6181179215.908792,
                                                "Bruce": 141606582.83870196,
                                                "Calwell": 190975814.2516695,
                                                "Casey": 2622676559.5893054,
                                                "Chisholm": 72753136.99542378,
                                                "Cooper": 61076488.86062691,
                                                "Corangamite": 577484449.44329,
                                                "Corio": 1168250929.5904396,
                                                "Deakin": 98325604.6393313,
                                                "Dunkley": 147768707.82965586,
                                                "Flinders": 628407176.8840953,
                                                "Gellibrand": 123127339.41818021,
                                                "Gippsland": 31954278842.762264,
                                                "Indi": 29168879581.278713,
                                                "Isaacs": 157743264.12605038,
                                                "Jagajaga": 137199575.01616597,
                                                "Kooyong": 59047063.164501056,
                                                "La Trobe": 1301951577.2203968,
                                                "Lalor": 175839798.9325303,
                                                "Mallee": 83390266014.52559,
                                                "Maribyrnong": 69888492.74177569,
                                                "Mcewen": 2288080225.3816295,
                                                "Melbourne": 39415531.29949789,
                                                "Menzies": 102131932.99025893,
                                                "Monash": 7833516784.431833,
                                                "Nicholls": 14114121837.121017,
                                                "Scullin": 173756723.3666137,
                                                "Wannon": 33565794702.612484,
                                                "Wills": 47111858.12994569,
                                                "Berowra": 756607218.8533256,
                                                "Blaxland": 59317411.68302002,
                                                "Calare": 32666723567.545666,
                                                "Chifley": 112707173.50006439,
                                                "Cowper": 7110762007.412807,
                                                "Cunningham": 496420418.4417343,
                                                "Dobell": 680849013.5861458,
                                                "Eden-Monaro": 31704242672.037907,
                                                "Farrer": 126698419963.51266,
                                                "Fowler": 62488477.01084343,
                                                "Gilmore": 6104579732.541229,
                                                "Grayndler": 34191320.77703141,
                                                "Greenway": 89579116.04513085,
                                                "Hughes": 357624639.8560632,
                                                "Hume": 2675346393.11572,
                                                "Hunter": 7242521263.439364,
                                                "Lindsay": 325218946.37201685,
                                                "Lyne": 15780182798.569221,
                                                "Macarthur": 306913986.40165627,
                                                "Mackellar": 208543031.13319728,
                                                "Macquarie": 4388915863.543869,
                                                "Mcmahon": 178562818.50641376,
                                                "Mitchell": 79283461.94634277,
                                                "New England": 75238849573.32271,
                                                "Newcastle": 136600396.05090922,
                                                "Page": 19230662247.062187,
                                                "Parkes": 407228254718.4335,
                                                "Paterson": 831835912.1305839,
                                                "Reid": 55081311.55810036,
                                                "Richmond": 2068432794.1779742,
                                                "Riverina": 52390906267.30796,
                                                "Robertson": 846734094.9512271,
                                                "Shortland": 150152969.19126356,
                                                "Watson": 50487818.802329645,
                                                "Werriwa": 110958350.76545186,
                                                "Whitlam": 3016763609.0392923,
                                                "Brand": 294283954.88537806,
                                                "Bullwinkel": 9500587811.944223,
                                                "Burt": 221698823.98321843,
                                                "Canning": 3718647111.700034,
                                                "Cowan": 107587716.38052757,
                                                "Curtin": 101611204.04251982,
                                                "Durack": 1411972193630.463,
                                                "Forrest": 6332282915.240249,
                                                "Fremantle": 166544621.3065567,
                                                "Hasluck": 258208922.04810125,
                                                "Moore": 101909819.288829,
                                                "O'Connor": 1092820212525.3754,
                                                "Pearce": 739450341.4003032,
                                                "Perth": 73456054.2608656,
                                                "Swan": 133011882.95798391,
                                                "Tangney": 107233999.38372006,
                                                "Bass": 7133844413.857011,
                                                "Braddon": 20650223436.39441,
                                                "Clark": 287567847.90811396,
                                                "Franklin": 5248103537.254256,
                                                "Lyons": 31465891509.9013,
                                                "Adelaide": 86494355.4000915,
                                                "Barker": 64378134015.46753,
                                                "Boothby": 107289439.0427778,
                                                "Grey": 907727441456.8156,
                                                "Kingston": 132919535.54232599,
                                                "Makin": 162408301.99221212,
                                                "Mayo": 8462853770.491209,
                                                "Spence": 501095423.6743442,
                                                "Sturt": 97700384.70947312,
                                                "Blair": 6466687014.306615,
                                                "Bonner": 183375799.29930827,
                                                "Bowman": 275029867.29490465,
                                                "Brisbane": 57435389.10985921,
                                                "Capricornia": 90716365878.26007,
                                                "Dawson": 14702849883.281992,
                                                "Dickson": 723758721.2266728,
                                                "Fadden": 383400916.1013847,
                                                "Fairfax": 991897837.2399374,
                                                "Fisher": 1155173092.759791,
                                                "Flynn": 132187430513.48091,
                                                "Forde": 417269732.48769313,
                                                "Petrie": 129191081.47938274,
                                                "Rankin": 130940116.94156869,
                                                "Ryan": 370220989.8569052,
                                                "Wide Bay": 13975568219.639923,
                                                "Wright": 7571534363.860414,
                                                "Lingiari": 1343355888276.2444,
                                                "Solomon": 181966697.25652018,
                                                "Bean": 1874986548.1752708,
                                                "Canberra": 312315193.6282977,
                                                "Fenner": 187782146.388916,
                                                "Gorton": 207466704.81595242,
                                                "Hawke": 1986679675.458412,
                                                "Holt": 214262158.19647476,
                                                "Hotham": 81003918.94249208,
                                                "Griffith": 57329779.201792866,
                                                "Groom": 5583628147.2836485,
                                                "Herbert": 1064450601.7249672,
                                                "Hinkler": 3824702080.70752,
                                                "Kennedy": 567094492150.0691,
                                                "Leichhardt": 148928783884.08304,
                                                "Lilley": 140758680.7815742,
                                                "Longman": 1100782952.691666,
                                                "Maranoa": 732248042092.8848,
                                                "Mcpherson": 217013594.53176102,
                                                "Moncrieff": 103418959.46132593,
                                                "Moreton": 109489014.90769486,
                                                "Oxley": 158417403.85699183
                                            }
                                    }
                            }
                    },
                "source": "pid"
            },
        "name" : "Project area of ",
        "description" : "Project area of a NESP 2 project",
    };