var westernAustralia = {
  "area":"2537412.7510852916",
  "description":"",
  "extent":{
    "geometry":{
      "datum":"",
      "fid":"cl2",
      "areaKmSq":2537412.75108529,
      "precision":"",
      "lga":[
        "Katanning (S)",
        "Coolgardie (S)",
        "Cue (S)",
        "Gingin (S)",
        "Denmark (S)",
        "Woodanilling (S)",
        "Northampton (S)",
        "York (S)",
        "Derby-West Kimberley (S)",
        "Mount Magnet (S)",
        "Mount Marshall (S)",
        "Mandurah (C)",
        "MacDonnell (S)",
        "Gnowangerup (S)",
        "Esperance (S)",
        "Cranbrook (S)",
        "Nungarin (S)",
        "Morawa (S)",
        "Melville (C)",
        "Merredin (S)",
        "Halls Creek (S)",
        "Cunderdin (S)",
        "Kalgoorlie/Boulder (C)",
        "Brookton (S)",
        "Leonora (S)",
        "Maralinga Tjarutja (AC)",
        "Claremont (T)",
        "Wagin (S)",
        "Menzies (S)",
        "Broome (S)",
        "Subiaco (C)",
        "Goomalling (S)",
        "Quairading (S)",
        "East Fremantle (T)",
        "Narrogin (S)",
        "Plantagenet (S)",
        "Narrogin (T)",
        "Yalgoo (S)",
        "Wongan-Ballidu (S)",
        "Donnybrook-Balingup (S)",
        "Exmouth (S)",
        "Trayning (S)",
        "Geraldton-Greenough (C)",
        "Gosnells (C)",
        "Kojonup (S)",
        "Kellerberrin (S)",
        "Toodyay (S)",
        "Three Springs (S)",
        "West Arthur (S)",
        "Busselton (S)",
        "Beverley (S)",
        "Belmont (C)",
        "Bassendean (T)",
        "Murchison (S)",
        "Mukinbudin (S)",
        "Mundaring (S)",
        "Mullewa (S)",
        "Manjimup (S)",
        "Kent (S)",
        "Joondalup (C)",
        "Kalamunda (S)",
        "Irwin (S)",
        "Jerramungup (S)",
        "East Pilbara (S)",
        "Cottesloe (T)",
        "Canning (C)",
        "Boyup Brook (S)",
        "Boddington (S)",
        "Kondinin (S)",
        "Bridgetown-Greenbushes (S)",
        "Cambridge (T)",
        "Shark Bay (S)",
        "Rockingham (C)",
        "Wyalkatchem (S)",
        "Kulin (S)",
        "Kwinana (T)",
        "Fremantle (C)",
        "Ravensthorpe (S)",
        "Port Hedland (T)",
        "Peppermint Grove (S)",
        "Perenjori (S)",
        "Narembeen (S)",
        "Nannup (S)",
        "Wandering (S)",
        "Murray (S)",
        "Victoria Plains (S)",
        "Vincent (T)",
        "Victoria Park (T)",
        "Victoria-Daly (S)",
        "Upper Gascoyne (S)",
        "Unincorporated SA",
        "Anangu Pitjantjatjara (AC)",
        "Ashburton (S)",
        "Augusta-Margaret River (S)",
        "Albany (C)",
        "Tammin (S)",
        "Cockburn (C)",
        "Chittering (S)",
        "Chapman Valley (S)",
        "Central Desert (S)",
        "Williams (S)",
        "Swan (C)",
        "Ngaanyatjarraku (S)",
        "Bunbury (C)",
        "Mosman Park (T)",
        "South Perth (C)",
        "Sandstone (S)",
        "Harvey (S)",
        "Moora (S)",
        "Armadale (C)",
        "Westonia (S)",
        "Wyndham-East Kimberley (S)",
        "Perth (C)",
        "Wanneroo (C)",
        "Stirling (C)",
        "Serpentine-Jarrahdale (S)",
        "Collie (S)",
        "Wiluna (S)",
        "Coorow (S)",
        "Yilgarn (S)",
        "Carnamah (S)",
        "Wickepin (S)",
        "Carnarvon (S)",
        "Bruce Rock (S)",
        "Dundas (S)",
        "Dumbleyung (S)",
        "Cuballing (S)",
        "Mingenew (S)",
        "Koorda (S)",
        "Nedlands (C)",
        "Pingelly (S)",
        "Roebourne (S)",
        "Dardanup (S)",
        "Laverton (S)",
        "Waroona (S)",
        "Meekatharra (S)",
        "Lake Grace (S)",
        "Northam (S)",
        "Corrigin (S)",
        "Broomehill-Tambellup (S)",
        "Bayswater (C)",
        "Dowerin (S)",
        "Dalwallinu (S)",
        "Dandaragan (S)",
        "Capel (S)"
      ],
      "bbox":"POLYGON((112.921493530273 -35.1939811706543,112.921493530273 -13.68922996521,129.001937866211 -13.68922996521,129.001937866211 -35.1939811706543,112.921493530273 -35.1939811706543))",
      "nrm":[
        "Perth",
        "Northern Territory",
        "Peel-Harvey",
        "Avon",
        "South Coast",
        "South West",
        "Rangelands",
        "Alinytjara Wilurara",
        "Northern Agricultural"
      ],
      "locality":"",
      "coordinates":[
        [
          [
            112.921493530273,
            -35.1939811706543
          ],
          [
            112.921493530273,
            -13.68922996521
          ],
          [
            129.001937866211,
            -13.68922996521
          ],
          [
            129.001937866211,
            -35.1939811706543
          ],
          [
            112.921493530273,
            -35.1939811706543
          ]
        ]
      ],
      "decimalLongitude":120.961715698242,
      "centre":[
        "122.18135980156345",
        "-25.466059061977788"
      ],
      "aream2":2536063780951.11,
      "decimalLatitude":-24.4416055679322,
      "pid":"6802849",
      "mvs":"Hummock grasslands",
      "uncertainty":"",
      "type":"pid",
      "name":"Western Australia",
      "state":[
        "South Australia (including Coastal Waters)",
        "Northern Territory (including Coastal Waters)",
        "Western Australia (including Coastal Waters)"
      ],
      "layerName":"Western Australian Biodiversity Science Research Priority Merged Regions",
      "mvg":"Hummock Grasslands",
      "ibra":[
        "Great Sandy Desert",
        "Geraldton Sandplains",
        "Mallee",
        "Coolgardie",
        "Carnarvon",
        "Nullarbor",
        "Victoria Bonaparte",
        "Murchison",
        "Hampton",
        "Central Kimberley",
        "Esperance Plains",
        "Little Sandy Desert",
        "Warren",
        "Jarrah Forest",
        "Gibson Desert",
        "Great Victoria Desert",
        "Avon Wheatbelt",
        "Yalgoo",
        "Gascoyne",
        "Swan Coastal Plain",
        "Pilbara",
        "Northern Kimberley",
        "Central Ranges",
        "Dampierland",
        "Tanami",
        "Ord Victoria Plain"
      ],
      "imcra4_pb":[
        "Central Western Shelf Province",
        "Central Western Shelf Transition",
        "Northwest Shelf Province",
        "Southwest Shelf Transition",
        "Southwest Shelf Province",
        "Northwest Shelf Transition",
        "Great Australian Bight Shelf Transition"
      ],
      "elect":[
        "TANGNEY",
        "SWAN",
        "BURT",
        "COWAN",
        "LINGIARI",
        "FORREST",
        "BRAND",
        "DURACK",
        "CURTIN",
        "CANNING",
        "STIRLING",
        "FREMANTLE",
        "PERTH",
        "HASLUCK",
        "PEARCE",
        "MOORE",
        "O'CONNOR",
        "GREY"
      ],
      "cmz":[
        "Swan Coastal Plain shrublands and woodlands",
        "North Australian tropical savanna woodlands",
        "Western Australian temperate sandplain woodlands",
        "South Western Australia temperate woodlands",
        "Arid shrublands and desert",
        "Esperance coastal shrublands and mallee",
        "South Western Australia temperate forests",
        "South Western Australia mallee woodlands"
      ],
      "other":[
        "Australian Coral Ecoregions",
        "RAMSAR wetland regions",
        "Directory of Important Wetlands",
        "National Native Title Register (NNTR, Determinations of Native Title) - boundaries and core attributes",
        "Indigenous Protected Areas 2013",
        "Indigenous Land Use Agreements"
      ],
      "gerSubRegion":[

      ]
    },
    "source":"pid"
  },
  "externalId":"",
  "geoIndex":{
    "coordinates":[
      [
        [
          -35.1939811706543,
          112.921493530273
        ],
        [
          -13.68922996521,
          112.921493530273
        ],
        [
          -13.68922996521,
          129.001937866211
        ],
        [
          -35.1939811706543,
          129.001937866211
        ],
        [
          -35.1939811706543,
          112.921493530273
        ]
      ]
    ],
    "type":"Polygon"
  },
  "isSciStarter":false,
  "name":"Project area for Project Name",
  "notes":"",
  "poi":[

  ],
  "projects":[
    "9072b8ce-f2d9-457c-b7a1-df76d799b1bd"
  ],
  "siteId":"69b2c5ca-122c-4145-a954-b0334b1d4f32",
  "status":"active",
  "type":""
};