---
appName:
  "biocollect"
layout:
  skin: "ala2"

server:
  servlet:
    session:
      timeout: 3600

app:
  default:
    hub: "ala"
  view:
    nocache: false
  http:
    header:
      userId: "X-ALA-userId"
      hostName: "X-ALA-hostname"

#External URL
aekosEnabled: false
enableReporting: true
bugherd:
  integration : false
emailFilter: "/[A-Z0-9._%-]+@csiro.au"
download:
  email:
    threshold: 100
notification:
  enabled: false
# Specific configurations used by Biocollect
facets:
  flimit: 15

pingDuration: 300000

headerAndFooter:
  baseURL: "https://www.ala.org.au/commonui-bs2" #"https://www.ala.org.au/commonui-bs2-v2/commonui-bs2"
  header:
    - contentType: "content"
      displayName: "Search"
      href: "/project/projectFinder"
    - contentType: "allrecords"
      displayName: "All records"
    - contentType: "content"
      displayName: "Sites"
      href: "/site/list"
    - contentType: "newproject"
      displayName: "New Project"
    - contentType: "admin"
      displayName: "Admin"
    - contentType: "login"
      displayName: "Logout"
  footer:
    - contentType: "content"
      displayName: "Search"
      href: "/project/projectFinder"
    - contentType: "allrecords"
      displayName: "All records"
    - contentType: "content"
      displayName: "Sites"
      href: "/site/list"
    - contentType: "newproject"
      displayName: "New Project"
    - contentType: "admin"
      displayName: "Admin"
    - contentType: "login"
      displayName: "Logout"

images:
  baseURL: "https://images.ala.org.au"

lists:
  baseURL: "https://lists.ala.org.au" # "https://lists-test.ala.org.au/public/speciesLists"
  commonFields: ['rawScientificName', 'matchedName', 'commonName']
  facetsToRemoveFromProjectFinderPage: ['projLifecycleStatus']

merit:
  baseURL: "https://fieldcapture-test.ala.org.au"

mdba:
  baseUrl: "http://mdba-test.ala.org.au"
  searchUrl: "/occurrences/search?fq=data_hub_uid:dh10#tab_mapView"

mobile:
  authKeyEnabled: true
  auth:
    check:
      url:  "https://m.ala.org.au/mobileauth/mobileKey/checkKey"

report:
  download:
    - header: 'Group'
      property: 'group'
    - header: 'Count'
      property: 'count'


pdfgen:
  baseURL: "https://pdfgen.ala.org.au/"

sld:
  polgon:
    default:
      url: "http://fish.ala.org.au/data/alt-dist.sld"
    highlight:
      url: "http://fish.ala.org.au/data/fc-highlight.sld"

speciesConfiguration:
  default: [
            "type": "ALL_SPECIES",
            "speciesDisplayFormat": "SCIENTIFICNAME(COMMONNAME)"
           ]


spatial:
   baseURL: "https://spatial.ala.org.au/"

upload:
   images:
      path: "/data/${appName}/images/"
   path: "/data/${appName}/"
   extensions:
      blacklist : ['exe','js','php','asp','aspx','com','bat']



grails:
    project:
      groupId: "au.org.ala"
    mail:
      poolSize: 1
    profile: web
    codegen:
        defaultPackage: au.org.ala.biocollect
    cache:
       ehcache:
            ehcacheXmlLocation: 'classpath:biocollect-ehcache.xml'
    mime:
        file:
          extensions: true
        use:
          accept:
            header: true
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
          maxFileSize: 26214400 #25Mb
          maxRequestSize: 26214400 #25Mb
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: none  #${ } will be html encoded if set to default to html
                scriptlets: html
                taglib: none
                staticparts: none
            sitemesh:
              preprocess: true

    resources:
      resourceLocatorEnabled: true
      adhoc:
          patterns: ['/images/*', '/css/*', '/js/*', '/plugins/*', '/vendor/*']
          includes: ['/images/**', '/css/**', '/js/**', '/plugins/**', '/vendor/**']

    scaffolding:
      templates:
        domainSuffix: 'Instance'
    json:
      legacy:
        builder: false
    # enabled native2ascii conversion of i18n properties files
    enable:
      native2ascii: true
    # packages to include in Spring bean scanning
    spring:
      bean:
        packages: []
    # whether to disable processing of multi part requests
    web:
      disable:
        multipart: false

    # request parameters to mask when logging exceptions
    exceptionresolver:
      params:
        exclude: ['password']



spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      exclude:
        - '*.gsp'
        - '**/*.gsp'
        - '*.gson'
        - '**/*.gson'
        - 'logback.groovy'
        - '*.properties'


# Spring Actuator Endpoints are Disabled by Default
webservice:
    connectTimeout: 6000000
    readTimeout: 6000000



markdown:
  hardwraps: true

# Sightings
coordinates:
  sources: ["Google maps", "Google earth", "GPS device", "camera/phone", "physical maps", "other"]
sighting:
  fields:
    excludes: ['errors','timeZoneOffset','eventDateNoTime','eventDateTime','class','log','constraints','$constraints']

  licenses: ['Creative Commons Attribution','Creative Commons Attribution-Noncommercial','Creative Commons Attribution-Share Alike','Creative Commons Attribution-Noncommercial-Share Alike']

sortFields: ['scientificName','commonName','eventDate','dateCreated','lastUpdated','locality','multimedia']
accuracyValues: [0,10,50,100,500,1000,5000,10000]
flag:
  issues: ['IDENTIFICATION','GEOCODING_ISSUE','TEMPORAL_ISSUE','HABITAT_ISSUE','--','INAPPROPRIATE_IMAGE']
showBiocacheLinks: false
identify:
  subgroupFacet: "names_and_lsid"
  enabled: true
projectdata:
  industries:
    enabled: false

userDetails:
  url: "${auth.baseURL}/userdetails/"

userDetailsById:
  path: "getUserDetails"
management:
  endpoints:
    jmx:
      exposure:
        exclude:
    enabled-by-default: false

# bootstrap4 theme
bootstrap4:
  themeDirectory: "/bootstrap4/scss"
  themeFileName: "styles"
  themeExtension: "scss"
  copyFromDir: "bootstrap4"
  copyToDir: "bootstrap4"

# used by ala-admin-plugin
skin:
  layout: "bs4"

---

grails:
  cors:
    enabled: true

---
#pwa
pwa:
  appUrl: "http://localhost:5173"
  cache:
    ignore: ["/image/upload", "/ws/attachment/upload"]
  maxAreaInKm: 25
  tileSize: 256
  apiKey: ""
  cacheVersion: "v3"
  oldCacheToDelete: "v2"
  serviceWorkerConfig:
      pathsToIgnoreCache: [ "/image/upload", "/ws/attachment/upload", "/ajax/keepSessionAlive", "/noop", '/pwa/sw.js', '/pwa/config.js', "/ws/species/speciesDownload" ]
      cachePathForRequestsStartingWith: [ "/pwa/bioActivity/edit/", "/pwa/createOrEditFragment/", "/pwa/bioActivity/index/", "/pwa/indexFragment/", "/pwa/offlineList" ]
      filesToPreCache: ["webjars/leaflet/0.7.7/dist/images/layers.png", "webjars/leaflet/0.7.7/dist/images/layers-2x.png", "webjars/leaflet/0.7.7/dist/images/marker-icon.png", "webjars/leaflet/0.7.7/dist/images/marker-icon-2x.png", "webjars/leaflet/0.7.7/dist/images/marker-shadow.png", "map-not-cached.png", "font-awesome/5.15.4/svgs/regular/image.svg"]
      baseMapPrefixUrl: "https://api.maptiler.com/maps/hybrid/256"
      noCacheTileFile: "map-not-cached.png"
  baseMapUrl: "${pwa.serviceWorkerConfig.baseMapPrefixUrl}/{z}/{x}/{y}.jpg?key="
  mapConfig:
    baseLayers:
      - code: 'maptilersatellite'
        displayText: 'Satellite'
        isSelected: true
        attribution: '<a href="https://www.maptiler.com/copyright/" target="_blank">© MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">© OpenStreetMap contributors</a>'
    overlays: [ ]

---
speciesCatalog:
  url: "To be set"
  fileName: "combined.zip"
  vernacularFileName: "vernacularname.txt"
  taxonFileName: "taxon.txt"
  totalFileName: "total.json"
  batchSize: 1000
  dir: "/data/biocollect/speciesCatalog"
  filters:
    language: "en"
    exclude:
      unrankedValue: "unranked"
  taxon:
    headerNames:
      guid: "taxonID"
      scientificName: "scientificName"
      rankString: "taxonRank"
      name: "scientificName"
  vernacular:
    headerNames:
      taxonID: "taxonID"
      vernacularName: "vernacularName"
      language: "language"
      preferred: "isPreferredName"
